### PR TITLE
Consider timezone when calculate timekey

### LINKED ISSUE #1986: file timezone problem
Fluentd version: td-agent 1.0.2

I want to transfer logfile from CentOS to CentOS by fluentd.
I could transfer file but file switches at incorrect time.
My timezone is +0900.

- output files (ls -l)
 rw-r--r-- 1 root root  34201618  5月 15 09:02 test-log.20180514
 rw-r--r-- 1 root root  40060437  5月 16 09:01 test-log.20180515
 rw-r--r-- 1 root root   5943936  5月 16 10:47 test-log.20180516

I want files switch at 00:00 but actually they switch at 09:00 everyday.
When I set time_slice_format = %Y%m%d_%H files switch correctly. (test.log.20180516_01 is created at 01:00 )

how can I solve it?

config (input) :
```
<source>
 type tail
 format none
 path /var/log/test-log
 pos_file /var/log/td-agent/test-log.pos
 tag hostfrom.test-log
</source>

<match *.*>
 type forward
 <server>
  host hostlog
  port 24224
 </server>
</match>
```

config (output) :
```
<source>
 @type forward
 bind 0.0.0.0
 port 24224
</source>

<match hostfrom.test-log>
 type file
 format single_value
 buffer_path /var/log/td-agent/buffer/test-log.buf
 path /log/test-log
 append true
 path_suffix
</match>
```

### PR DESCRIPTION
**Pull request by okkez**
Because the timestamp of the midnight cannot be divisible by 86400 in
localtime (JST). The timestamp of the midnight is divisible by 86400
only in UTC. Therefore we must consider offset from UTC in localtime.

For example, at `2018-07-04 01:23:23 +0900`:

If timekey is 86400 and path template is `/log/%Y%m%d.log`.
In previous version, extract path template to `/log/20180703.log`.
In this version, extract path template to `/log/20180704.log`.

Fix #1986

### CODE REVIEW

**Comment by repeatedly** [comment]
Test failed. Could you check it?

File: test/plugin/test_out_file.rb [hunk 1]
```diff
@@ -557,6 +557,42 @@ def parse_system(text)
...
+      formatted_lines = %[2011-01-02T03:14:15+09:00\ttest\t{"a":1}\n] + %[2011-01-02T03:14:15+09:00\ttest\t{"a":2}\n]
+
+      write_once = ->(){
+        d = create_driver %[
+          path #{TMP_DIR}/out_file_test
+          compress gz
+          append true
+          <buffer>
+            timekey_use_utc false
+            timekey_zone Asia/Tokyo
```
Comment (repeatedly) [inline test/plugin/test_out_file.rb]: Could you use "+0900" like value?
I'm not sure but test on Windows fails.

Comment (repeatedly) [reply test/plugin/test_out_file.rb]: Just commit the fix :)

File: lib/fluent/plugin/output.rb [hunk 2]
```diff
@@ -825,6 +822,16 @@ def metadata(tag, time, record)
         end
       end
 
+      def calculate_timekey(time)
+        time_int = time.to_i
+        if @buffer_config.timekey_use_utc
+          (time_int - (time_int % @buffer_config.timekey)).to_i
+        else
+          offset = Time.at(time_int).utc_offset
```
Comment (repeatedly) [inline lib/fluent/plugin/output.rb]: Should consider `timekey_zone` value instead of `utc_offset`?

Comment (okkez) [reply lib/fluent/plugin/output.rb]: Maybe yes. How about the following function?

```diff
diff --git a/lib/fluent/timezone.rb b/lib/fluent/timezone.rb
index bb6fa868..0e79dd03 100644
--- a/lib/fluent/timezone.rb
+++ b/lib/fluent/timezone.rb
@@ -139,5 +139,17 @@ module Fluent
 
       return nil
     end
+
+    def self.utc_offset(time, timezone)
+      return 0 if timezone.nil?
+
+      case timezone
+      when NUMERIC_PATTERN
+        Time.zone_offset(timezone)
+      when NAME_PATTERN
+        tz = TZInfo::Timezone.get(timezone)
+        tz.period_for_utc(time).utc_total_offset
+      end
+    end
   end
 end
```

Comment (repeatedly) [reply lib/fluent/plugin/output.rb]: looks good

File: lib/fluent/plugin/output.rb [hunk 3]
```diff
@@ -825,6 +822,16 @@ def metadata(tag, time, record)
         end
       end
 
+      def calculate_timekey(time)
+        time_int = time.to_i
+        if @buffer_config.timekey_use_utc
```
Comment (repeatedly) [inline lib/fluent/plugin/output.rb]: accessing object member is slower than accessing instance variable.
`@timekey_use_utc = @buffer_config.timekey_use_utc` in `configure` is better.

File: lib/fluent/plugin/output.rb [hunk 4]
```diff
@@ -825,6 +824,16 @@ def metadata(tag, time, record)
         end
       end
 
+      def calculate_timekey(time)
+        time_int = time.to_i
+        if @timekey_use_utc
+          (time_int - (time_int % @timekey)).to_i
+        else
+          offset = Fluent::Timezone.utc_offset(time, @timekey_zone)
```
Comment (repeatedly) [inline lib/fluent/plugin/output.rb]: Check `@timekey_zone` format everytime is slower.
This code is called in each emit so need to avoid extra cost.
Cache the result is better.

File: test/plugin/test_out_file.rb [hunk 5]
```diff
@@ -557,6 +557,42 @@ def parse_system(text)
     check_gzipped_result(path, formatted_lines * 3)
   end
 
+  test 'append when JST' do
```
Comment (repeatedly) [inline test/plugin/test_out_file.rb]: Could you add more test with different time and timezone, e.g. `timekey_zone` is `+09:00` and actual time is `+02:00`

File: lib/fluent/plugin/output.rb (hunk 4 above)
Comment (okkez) [reply lib/fluent/plugin/output.rb]: Hmm, we should consider DST. The naive cache is not good for DST.
What should we do?

Comment (repeatedly) [reply lib/fluent/plugin/output.rb]: I see.
One way is generating `calculate_timekey` method in `configure`.
For numeric pattern, the offset value can be embbed directly.
For name pattern, embed getting tz data in the body.
How about this?

**Comment by repeatedly** [comment]
Thanks!

**Comment by repeatedly** [comment]
I released v1.2.4.rc1 for testing this patch.
