### PR TITLE
Fix race condition of out_secondary_file

### LINKED ISSUE #4080: `SecondaryFileOutput` sometimes appends logs even when `append false` in multiple workers
### Describe the bug

This logic causes race condition issues in multiple workers when `append false`.

https://github.com/fluent/fluentd/blob/e58fd66d71bf3df046f2fd29980521e59f6fcb83/lib/fluent/plugin/out_secondary_file.rb#L118-L129

### To Reproduce

Run the fluentd with the following config for about 1 minute.

```console
bundle exec fluentd -c fluent.conf
```

Then we can find some files where logs with different tags are mixed in the same file although the chunk-key was `tag` and `append` was `false`.

```
2023-03-03T19:53:28+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:29+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:30+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:31+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:32+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:33+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:34+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:35+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:36+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:37+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:38+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:28+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:29+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:30+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:31+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:32+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:33+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:34+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:35+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:36+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:37+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:38+09:00	aaa.fuga.bbb	{"message":"fuga"}
```

### Expected behavior

Each chunk is separated into a file.

File-A

```
2023-03-03T19:53:28+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:29+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:30+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:31+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:32+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:33+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:34+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:35+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:36+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:37+09:00	aaa.hoge.bbb	{"message":"hoge"}
2023-03-03T19:53:38+09:00	aaa.hoge.bbb	{"message":"hoge"}
```

File-B

```
2023-03-03T19:53:28+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:29+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:30+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:31+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:32+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:33+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:34+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:35+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:36+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:37+09:00	aaa.fuga.bbb	{"message":"fuga"}
2023-03-03T19:53:38+09:00	aaa.fuga.bbb	{"message":"fuga"}
```

### Your Environment

```markdown
- Fluentd version: fluentd 1.15.3
- Operating system: Ubuntu 20.04.5 LTS (Focal Fossa)
- Kernel version: 5.15.0-60-generic
```

### Your Configuration

```apache
<system>
  workers 4
</system>

<source>
  @type sample
  tag aaa.hoge.bbb
  sample {"message": "hoge"}
</source>

<source>
  @type sample
  tag aaa.fuga.bbb
  sample {"message": "fuga"}
</source>

<source>
  @type sample
  tag aaa.foo.bbb
  sample {"message": "foo"}
</source>

<match aaa.**>
  @type file
  path /test/fluentd/log/${tag}/fluentd.log
  append true
  <buffer tag>
    @type file
    path /test/fluentd/buffer
    flush_mode interval
    flush_interval 10s
    retry_max_times 1
  </buffer>
  <secondary>
    @type secondary_file
    directory /test/fluentd/error/
    append false
  </secondary>
</match>
```

### Your Error Log

```shell
Error logs are not related to this issue.
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by daipom**
**Which issue(s) this PR fixes**: 
Fixes #4080

**What this PR does / why we need it**: 
For solving race condition issues of `out_secondary_file`.

* Note: Similar problem in `out_file`: #3808.

**Docs Changes**:
Not needed.

**Release Note**: 
Same as the title.

### CODE REVIEW

**Comment by daipom** [comment]
I have confirmed this solves #4080.

File: lib/fluent/plugin/out_secondary_file.rb [hunk 1]
```diff
@@ -117,15 +116,45 @@ def has_time_format?(str)
...
+          break unless File.exist?(path)
           i += 1
         end
+        lock_if_needed(path) do
+          # If multiple processes select the same path and another process
+          # entered this locking block first, the file should already exist
+          # and this process should retry to find new path.
+          raise FileAlreadyExist if File.exist?(path)
+          yield path
+        end
```
Comment (daipom) [inline lib/fluent/plugin/out_secondary_file.rb:139]: I just noticed that this logic perhaps must consider working on multiple threads, not only multiple processes.
I'll do additional tests and make the fix if necessary.

Comment (daipom) [reply lib/fluent/plugin/out_secondary_file.rb:139]: Test for fe65b4f37730e718ec23528142429f42d0961515.

Use the same way and the same environment as

* #4080#issuecomment-1455695378

Result: 

| workers | flush_thread_count |   percentage  |
|---------|--------------------|---------------|
|       1 |                 16 | 45.5% (10/22) |
|       3 |                  1 | 0.0% (0/51)   |

So the current fix is not enough.

**Comment by daipom** [comment]
Test for  c95b52a.

Use the same way and the same environment as

* https://github.com/fluent/fluentd/issues/4080#issuecomment-1455695378

Result: 

| workers | flush_thread_count | percentage (1st) | percentage (2nd) |
|---------|--------------------|------------------|------------------|
|       1 |                 16 | 0.0% (0/111)     | 0.0% (0/42)      |
|       3 |                  1 | 0.0% (0/27)      | 0.0% (0/27)      |
|       3 |                  8 | 0.0% (0/267)     | 0.0% (0/29)      |

File: lib/fluent/plugin/out_secondary_file.rb [hunk 2]
```diff
@@ -61,34 +61,40 @@ def configure(conf)
...
     end
 
     def multi_workers_ready?
-      ### TODO: add hack to synchronize for multi workers
       true
     end
 
+    def start
+      super
+      extend WriteLocker
```
[the remark this answers is not in the document]
Comment (daipom) [reply lib/fluent/plugin/out_secondary_file.rb:74]: I'm not sure how I should handle these Ruby features...
What I thought was as follows.

* I just wanted to clean up the methods by combining some specific function methods into a module.
* The `WriteLocker` module depends on the instance members of `SecondaryFileOutput`.
* So I felt uncomfortable with the form in which `SecondaryFileOutput` inherits `WriteLocker`.
  * I thought the dependency was reversed.

File: lib/fluent/plugin/out_secondary_file.rb [hunk 3]
```diff
@@ -61,34 +61,40 @@ def configure(conf)
...
+      @write_mutex = Mutex.new
```
[the remark this answers is not in the document]
Comment (daipom) [reply lib/fluent/plugin/out_secondary_file.rb:75]: Understood! I will fix this!

File: test/command/test_cat.rb [hunk 4]
```diff
@@ -83,6 +83,7 @@ def test_cat_json
   sub_test_case "msgpack" do
     def test_cat_secondary_file
       d = create_secondary_driver
+      d.instance_start
```
[the remark this answers is not in the document]
Comment (daipom) [reply test/command/test_cat.rb:86]: Hmm, even if we don't overwrite `start` method in `SecondaryFileOutput`, I wonder if it's really OK not to call `instance_start`.

Wouldn't it be correct to always call `instance_start` before calling the `instance` operation directly?

File: lib/fluent/plugin/out_secondary_file.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (daipom) [reply lib/fluent/plugin/out_secondary_file.rb:74]: Hmm, should I just write the methods directly under the `SecondaryFileOutput`, not using `module`?

[the remark this answers is not in the document]
Comment (ashie) [reply lib/fluent/plugin/out_secondary_file.rb:74]: In this case I prefer not using module since there aren't so many code in this plugin for now.

BTW methods in `WriteLocker` might be useful for other output plugins, so place them just under `Fluent::Plugin::Output` might be better.

[the remark this answers is not in the document]
Comment (daipom) [reply lib/fluent/plugin/out_secondary_file.rb:74]: Indeed! I will try it!

File: lib/fluent/plugin/out_secondary_file.rb [hunk 5]
```diff
@@ -61,34 +61,40 @@ def configure(conf)
 
       @dir_perm = system_config.dir_permission || Fluent::DEFAULT_DIR_PERMISSION
       @file_perm = system_config.file_permission || Fluent::DEFAULT_FILE_PERMISSION
+      @need_worker_lock = system_config.workers > 1
+      @need_thread_lock = @primary_instance.buffer_config.flush_thread_count > 1
```
[the remark this answers is not in the document]
Comment (daipom) [reply lib/fluent/plugin/out_secondary_file.rb:65]: It seems that we don't need to consider it.
`Secondary`'s primary must have its `buffer_config`.

https://github.com/fluent/fluentd/blob/v1.15.3/lib/fluent/plugin/output.rb#L285-L301

[the remark this answers is not in the document]
Comment (daipom) [reply lib/fluent/plugin/out_secondary_file.rb:65]: In addition, even if `buffer` section is not defined in the primary, `buffer_config` will be initialized by its default values.

File: lib/fluent/plugin/out_secondary_file.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (daipom) [reply lib/fluent/plugin/out_secondary_file.rb]: Fixed at ce32ac57a07121d69adf30d3b543ea11041ce613.

File: lib/fluent/plugin/out_secondary_file.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (daipom) [reply lib/fluent/plugin/out_secondary_file.rb]: Fixed at ce32ac57a07121d69adf30d3b543ea11041ce613.

**Comment by daipom** [comment]
Test for ce32ac57a07121d69adf30d3b543ea11041ce613.

Use the same way (`append false`) and the same environment as

* https://github.com/fluent/fluentd/issues/4080#issuecomment-1455695378

Result: 

| workers | flush_thread_count | percentage|
|---------|--------------------|------------------|
|       3 |                  8 | 0.0% (0/21)    |

I plan to do more tests at the end of this PR.

**Comment by daipom** [comment]
I will add some unit tests for the lock feature, although it is hard to test race condition strictly.

**Comment by daipom** [comment]
@ashie Could you please check if the direction of this fix is OK?

File: lib/fluent/plugin/output.rb [hunk 6]
```diff
@@ -597,6 +598,47 @@ def terminate
...
+
+      def get_worker_lock_if_need(name)
+        need_worker_lock = system_config.workers > 1
+        unless need_worker_lock
+          yield
+          return
+        end
+        acquire_worker_lock(name) do
+          yield
+        end
```
Comment (ashie) [inline lib/fluent/plugin/output.rb:628]:
```suggestion
        if need_worker_lock
          acquire_worker_lock(name) { yield }
        else
          yield
        end
```

File: lib/fluent/plugin/output.rb [hunk 7]
```diff
@@ -597,6 +598,47 @@ def terminate
...
+
+      def get_flush_thread_lock_if_need
+        need_thread_lock = actual_flush_thread_count > 1
+        unless need_thread_lock
+          yield
+          return
+        end
+        @flush_thread_mutex.synchronize do
+          yield
+        end
```
Comment (ashie) [inline lib/fluent/plugin/output.rb:639]:
```suggestion
        if need_thread_lock
          @flush_thread_mutex.synchronize { yeild }
        else
          yield
        end
```

File: lib/fluent/plugin/output.rb [hunk 8]
```diff
@@ -597,6 +598,47 @@ def terminate
...
+      # threads in the same process.
+      def lock_if_need(worker_lock_name)
+        get_worker_lock_if_need(worker_lock_name) do
+          get_flush_thread_lock_if_need do
+            yield
+          end
+        end
+      end
+
+      def get_worker_lock_if_need(name)
```
Comment (ashie) [inline lib/fluent/plugin/output.rb:620]: The prefix of the method name seems inconsistent (`get` vs `acquire`).

File: lib/fluent/plugin/output.rb (hunk 6 above)
Comment (daipom) [reply lib/fluent/plugin/output.rb:628]: Cool! Thanks for your advice!

File: test/command/test_cat.rb (hunk 4 above)
[the remark this answers is not in the document]
Comment (daipom) [reply test/command/test_cat.rb:86]: Indeed! I will remove this diff from this PR for now.

File: lib/fluent/plugin/output.rb (hunk 8 above)
Comment (daipom) [reply lib/fluent/plugin/output.rb:620]: Indeed. I will use `acquire`.

Comment (daipom) [reply lib/fluent/plugin/output.rb]: Fixed!

File: test/command/test_cat.rb (hunk 4 above)
[the remark this answers is not in the document]
Comment (daipom) [reply test/command/test_cat.rb]: Removed!

**Comment by daipom** [comment]
I will test this issue again, and add some tests for this new lock feature.

**Comment by daipom** [comment]
Test for edcbd4b6a9cf2e83c2c88e34e7a103f3a4786314.

Use the same way (`append false`) and the same environment as

* https://github.com/fluent/fluentd/issues/4080#issuecomment-1455695378

Result: 

| workers | flush_thread_count | percentage (1st) | percentage (2nd) |
|---------|--------------------|------------------|------------------|
|       1 |                 16 | 0.0% (0/24)      | 0.0% (0/39)      |
|       3 |                  1 | 0.0% (0/27)      | 0.0% (0/21)      |
|       3 |                  8 | 0.0% (0/36)      | 0.0% (0/33)      |

**Comment by daipom** [comment]
> I will test this issue again, and add some tests for this new lock feature.

Done.

File: lib/fluent/plugin/output.rb [hunk 9]
```diff
@@ -597,6 +598,43 @@ def terminate
...
+        return @buffer_config.flush_thread_count unless @as_secondary
+        @primary_instance.buffer_config.flush_thread_count
+      end
+
+      # Run the passed block in the appropriate lock condition for multiple threads and workers.
+      # The lock between workers is made for every `worker_lock_name`.
+      # (For multiple workers, the lock is shared if `worker_lock_name` is the same value).
+      # For multiple threads, `worker_lock_name` is not used, and the lock is shared by all
+      # threads in the same process.
+      def acquire_lock_if_need(worker_lock_name)
```
Comment (ashie) [inline lib/fluent/plugin/output.rb:612]: I feel it's not Rubyish naming (original `acquire_worker_lock` is so too though).
`synchronize_foobar` might be better but I don't have good concrete idea for `foobar` to express it.
(`worker_and_flush_thread` is too redundant.)

@kou Do you have any idea for it?

Comment (kou) [reply lib/fluent/plugin/output.rb:612]: `synchronize_path(path)`?
Or `guard_path(path)`?

Comment (daipom) [reply lib/fluent/plugin/output.rb:612]: Thanks for your advice!

I have one point of concern.
Since the argument `path` is not used in the case of multiple threads, isn't `ooxx_path` misleadable?

Comment (daipom) [reply lib/fluent/plugin/output.rb:612]: How about simply `synchronize(path)`?

Comment (kou) [reply lib/fluent/plugin/output.rb:612]: > Since the argument `path` is not used in the case of multiple threads, isn't `ooxx_path` misleadable?

Sorry but I can't understand the point. `synchronize_path(path) {...}` ensures `path` processable only by the current thread in the current process. `synchronize_path` does or does not something against `path` is details of `synchronize_path`. `synchronize_path` users should not care about it.

BTW, another candidate `use_path(path)`.

> How about simply `synchronize(worker_lock_path)`?

I object it. Because `Output`'s main responsibility isn't synchronization. So only `synchronize` is ambitious. For example, `Output` has two `Mutex`s. It means that there are at least two synchronization units in `Output`.

`Mutex#synchronize` is OK because `Mutex`'s main responsibility is one synchronization.

Comment (daipom) [reply lib/fluent/plugin/output.rb:612]: Thanks for your detailed explanation! I see! I understand!

Although this does NOT provide exclusive processing for each `path` (but for all threads), it after all means that this ensures the `path` processable only be the current thread.
So we don't need to concern that the `path` is not used in the case of multiple threads.

https://github.com/fluent/fluentd/blob/f23e7e689c813a3040610e8f6b5958be3a369c28/lib/fluent/plugin/output.rb#L629-L636

Comment (daipom) [reply lib/fluent/plugin/output.rb]: Fixed! Thanks for your advice! @ashie @kou !

**Comment by daipom** [comment]
By the way, might `Squash merge` be better when merging this?

File: test/plugin/test_output.rb [hunk 10]
```diff
@@ -1072,4 +1072,263 @@ def invoke_slow_flush_log_threshold_test(i)
...
+      }
+    )
+    test "actual_flush_thread_count" do |data|
+      o = create_output(data[:output_type])
+      o.configure(data[:config])
+      assert_equal data[:expected], o.actual_flush_thread_count
+    end
+
+    data(
+      "Buffered with singile thread",
```
[the remark this answers is not in the document]
Comment (daipom) [reply test/plugin/test_output.rb]: Thanks! Fixed!

**Comment by ashie** [comment]
Thanks!

**Comment by daipom** [comment]
Thanks for your review! @ashie @kou !
