### PR TITLE
fix data lost on decompression

### LINKED ISSUE #2546: compressable.rb lost some data on decompression
When sender fluend enable compress gzip, reciever fluend lost some data.

I put logging code to lib/fluent/plugin/compressable.rb, debug messages show unused is nil, but input stream is not EOF.
unused.nil? does not show end of stream.

```
--- compressable.rb-	2018-10-11 12:11:31.000000000 +0900
+++ compressable.rb	2019-08-08 13:26:25.589042228 +0900
@@ -64,6 +64,7 @@
           unused = gz.unused
           gz.finish
 
+          $log.debug "string_decompress", unused: (unused.nil? ? "nil" : "defined"), eof: (io.eof ? "EOF" : "not")
           break if unused.nil?
           adjust = unused.length
           io.pos -= adjust
```

```
2019-08-08 13:19:16 +0900 [debug]: #0 string_decompress unused="defined" eof="not"
2019-08-08 13:19:16 +0900 [debug]: #0 string_decompress unused="defined" eof="not"
2019-08-08 13:19:16 +0900 [debug]: #0 string_decompress unused="nil" eof="not"
```

I change check eof, then is works fine.

```
--- a/lib/fluent/plugin/compressable.rb
+++ b/lib/fluent/plugin/compressable.rb
@@ -64,9 +64,11 @@ module Fluent
           unused = gz.unused
           gz.finish
 
-          break if unused.nil?
-          adjust = unused.length
-          io.pos -= adjust
+          unless unused.nil?
+            adjust = unused.length
+            input.pos -= adjust
+          end
+          break if io.eof?
         end
 
         out
```

### PR DESCRIPTION
**Pull request by komeda-shinji**
**Which issue(s) this PR fixes**: 
Fixes #2546

in `string_decompress()`, `gz.read` loop break when `unused.nil?`,  
but `unused.nil?` does not show end of stream.
It cause data lost.

loop shoud be break when eof.

### CODE REVIEW

**Comment by repeatedly** [comment]
Thanks for the patch!

Could you follow DCO?
And do you have a failure case to check the behaviour in test?

**Comment by komeda-shinji** [comment]
I have failure case data, but I cannot provide because it contains privacy data.
I try to create failure case data, but It is too hard and unsuccessful yet.

**Comment by komeda-shinji** [comment]
This script generates failure case data for string_decompress easily.

```
require 'stringio'
require 'zlib'
require 'securerandom'

def compress(data, **kwargs)
  output_io = kwargs[:output_io]
  io = output_io || StringIO.new
  Zlib::GzipWriter.wrap(io) do |gz|
    gz.write data
  end

  output_io || io.string
end

def string_decompress(compressed_data)
  io = StringIO.new(compressed_data)

  out = ''
  loop do
    gz = Zlib::GzipReader.new(io)
    out << gz.read
    unused = gz.unused
    gz.finish

    break if unused.nil?
    adjust = unused.length
    io.pos -= adjust
  end

  out
end

def create_data
  data = []
  10.times do
    data << SecureRandom.base64(1990) + "\n"
  end
  data
end
    
def find_failure
  data = []
  found = false
  loop do
    data = create_data

    indata = ''
    for d in data do
      indata << compress(d)
    end
    
    io = StringIO.new(indata)
    out = ''
    loop do
      gz = Zlib::GzipReader.new(io)
      out << gz.read
      unused = gz.unused
      gz.finish
    
      puts unused: unused.nil? ? "nil" : unused.length, eof: io.eof? ? "EOF" : "not"
      found = true if unused.nil? and not io.eof?
      unless unused.nil?
        adjust = unused.length
        io.pos -= adjust
      end
      break if io.eof
    end
    break if found
  end
  data
end

failure_case = find_failure

indata = ''
for d in failure_case do
  indata << compress(d)
end
outdata = string_decompress(indata)

puts failure_case
puts "---"
puts outdata
```

File: lib/fluent/plugin/compressable.rb [hunk 1]
```diff
@@ -64,9 +64,11 @@ def string_decompress(compressed_data)
           unused = gz.unused
           gz.finish
 
-          break if unused.nil?
-          adjust = unused.length
-          io.pos -= adjust
+          unless unused.nil?
+            adjust = unused.length
+            input.pos -= adjust
```
Comment (repeatedly) [inline lib/fluent/plugin/compressable.rb]: Use `io` instead of `input` here.

Comment (komeda-shinji) [reply lib/fluent/plugin/compressable.rb]: Oh! It's my msitake, thank you.

**Comment by repeatedly** [comment]
Thanks!
I will consider adding test with your script.
