### PR TITLE
Don't raise exception when each message size is smaller than chunk_limit_size

### LINKED ISSUE #1849: Large message overflow logic incorrect
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version. v1.0.2 (also seems to be a problem on master right now)

I have a use case that allows for very log messages. While load testing using 2m buffers, I noticed that if I try to quickly jam these messages through back-to-back, the system will complain:

```
a 524596bytes record is larger than buffer chunk limit size
``` 

Looking at the code, I see the test for a single record overflowing the current chunk in `write_step_by_step`:

```ruby
                  if split.size == 1 && original_bytesize == 0
                    big_record_size = format ? format.call(split).bytesize : split.first.bytesize
                    raise BufferChunkOverflowError, "a #{big_record_size}bytes record is larger than buffer chunk limit size"
                  end
```

Since `original_bytesize` is set outside of the inner loop, it does not detect if the current split is the first chunk. The fix to this is straightforward enough, but the retry logic isn't clever enough to do something different the next time.

Ideally, we would know ahead of time that the message would overflow the buffer and just not write it. I imagine the code does not take the approach for the sake of efficiency. It would be nice if there was something like the `commit` and `rollback` functionality for use while constructing the chunk, perhaps `mark()` and `rewindToMark()` functions, or maybe even restructure `append` and `concat` to take blocks and allow for rewinding on failure.

I took a stab at some minimal change, but found that I don't have a full appreciation for the nuance of this function's existing behavior, given the various assertions that failed in my attempts to fix this bug. It does seem that the underlying assumption of the current code is that records are small in comparison to the buffer so that the `chunk_full_threshold` will always be crossed while filling a chunk. I can probably work around this issue by either increasing my buffer size, or changing the `chunk_full_threshold`. 

Here is a test that shows the problem adding one message that fills half the buffer, and then another that goes one byte over (added to 'with configuration for test with lower limits` sub_test_case):
```ruby
    test '#write does not raise BufferOverflowError when chunk is not empty' do
      m = @p.metadata(timekey: Time.parse('2016-04-11 16:40:00 +0000').to_i)

      assert_nothing_raised Fluent::Plugin::Buffer::BufferOverflowError do
        @p.write({m => ["a" * 512, "b" * 513 ]})
      end
    end
```

Commit with new test: https://github.com/amread/fluentd/commit/d0653aa80d3022b6708303176475280f2fb29af5

### PR DESCRIPTION
**Pull request by kenhys**
Follow up #3553

In the previous versions, even though each record size is smaller
than chunk limit size, but whole message size exceeds
chunk limit size, BufferChunkOverflowError is raised unexpectedly.

For example, if chunk limit size is 1_280_000, process 3 event
stream (every 1_000_00 bytes), it throws an exception like this:

  Fluent::Plugin::Buffer::BufferChunkOverflowError(<a 1000025 bytes
  record (nth: 1) is larger than buffer chunk limit size, a 1000025
  bytes record (nth: 2) is larger than buffer chunk limit size>)

Now changed not to raise exception if it's record size is smaller
enough than chunk limit size.

The idea is based on that adding byte size is smaller than chunk
limit size, chunk should be unstaged and pushed into queue,
If not, it should be skipped like #3553.

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>

**Which issue(s) this PR fixes**: 

Fixes #1849

**What this PR does / why we need it**: 

**Docs Changes**:

**Release Note**:

### CODE REVIEW

**Comment by kenhys** [comment]
updates about error message is split into #3562

**Comment by kenhys** [comment]
This PR relies on `adding_bytes`, it might not be implemented 3rd party buffer plugin.

**Comment by kenhys** [comment]
rebased with the recent master.

**Comment by kenhys** [comment]
This PR will not be merged for v1.14.3.

**Comment by cosmo0920** [comment]
> This PR will not be merged for v1.14.3.

This PR needs to be more testing required?

**Comment by ashie** [comment]
Yes, we need further checking for this.
Skip v1.14.3.

File: lib/fluent/plugin/buffer.rb [hunk 1]
```diff
@@ -799,13 +803,23 @@ def write_step_by_step(metadata, data, format, splits_count, &block)
...
                   if split.size == 1 && original_bytesize == 0
-                    # It is obviously case that BufferChunkOverflowError should be raised here,
-                    # but if it raises here, already processed 'split' or
-                    # the proceeding 'split' will be lost completely.
-                    # so it is a last resort to delay raising such a exception
-                    errors << "concatenated/appended a #{adding_bytes} bytes record (nth: #{writing_splits_index}) is larger than buffer chunk limit size (#{@chunk_limit_size})"
-                    writing_splits_index += 1
-                    next
+                    # FIXME: adding_bytes should be implemented as an official chunk API in the future
+                    if adding_bytes.is_a?(Integer) && adding_bytes < @chunk_limit_size
```
Comment (ashie) [inline lib/fluent/plugin/buffer.rb:807]: I'm not sure but `adding_bytes` might be able to calculate at caller side like this, because `adding_bytes` is cleared at `chunk.commit`, `chunk.rollback`, `chunk.purge`:

```diff
diff --git a/lib/fluent/plugin/buffer.rb b/lib/fluent/plugin/buffer.rb
index 5877af93..4df0dcb9 100644
--- a/lib/fluent/plugin/buffer.rb
+++ b/lib/fluent/plugin/buffer.rb
@@ -767,7 +767,7 @@ module Fluent
             raise ShouldRetry unless chunk.writable?
             staged_chunk_used = true if chunk.staged?
 
-            original_bytesize = chunk.bytesize
+            original_bytesize = before_bytesize = chunk.bytesize
             begin
               while writing_splits_index < splits.size
                 split = splits[writing_splits_index]
@@ -778,6 +778,7 @@ module Fluent
                     # so, keep already processed 'split' content here.
                     # (allow performance regression a bit)
                     chunk.commit
+                    before_bytesize = chunk.bytesize
                   else
                     big_record_size = formatted_split.bytesize
                     if big_record_size > @chunk_limit_size
@@ -788,6 +789,7 @@ module Fluent
                     elsif chunk.bytesize + big_record_size > @chunk_limit_size
                       # No doubt that the split is expected to cause size over, keep 'split' content here.
                       chunk.commit
+                      before_bytesize = chunk.bytesize
                     end
                   end
                 end
@@ -797,14 +799,14 @@ module Fluent
                 else
                   chunk.append(split, compress: @compress)
                 end
+                adding_bytes = chunk.bytesize - before_bytesize
 
                 if chunk_size_over?(chunk) # split size is larger than difference between size_full? and size_over?
-                  adding_bytes = chunk.instance_eval { @adding_bytes } || "N/A" # 3rd party might not have 'adding_bytes'
                   chunk.rollback
+                  before_bytesize = chunk.bytesize
 
                   if split.size == 1 && original_bytesize == 0
-                    # FIXME: adding_bytes should be implemented as an official chunk API in the future
-                    if adding_bytes.is_a?(Integer) && adding_bytes < @chunk_limit_size
+                    if adding_bytes < @chunk_limit_size
                       # already processed content is kept after rollback, then unstaged chunk should be queued.
                       # After that, re-process current split again (new chunk should be allocated, to do it, modify @stage and so on)
                       synchronize { @stage.delete(modified_metadata) }
```

Comment (kenhys) [reply lib/fluent/plugin/buffer.rb]: Thanks, this suggestion is more good approach to do the job.

**Comment by kenhys** [comment]
I've followed suggested approach (as before_bytesize is too general, so it was changed to represent what it is)

**Comment by ashie** [comment]
I'm still checking this, especially the difference of `original_bytesize` and `committed_bytesize`...

File: lib/fluent/plugin/buffer.rb [hunk 2]
```diff
@@ -793,19 +799,29 @@ def write_step_by_step(metadata, data, format, splits_count, &block)
...
                   if split.size == 1 && original_bytesize == 0
-                    # It is obviously case that BufferChunkOverflowError should be raised here,
-                    # but if it raises here, already processed 'split' or
-                    # the proceeding 'split' will be lost completely.
-                    # so it is a last resort to delay raising such a exception
-                    errors << "concatenated/appended a #{adding_bytes} bytes record (nth: #{writing_splits_index}) is larger than buffer chunk limit size (#{@chunk_limit_size})"
-                    writing_splits_index += 1
-                    next
+                    if adding_bytes < @chunk_limit_size
+                      # As already processed content is kept after rollback, then unstaged chunk should be queued.
```
Comment (ashie) [inline lib/fluent/plugin/buffer.rb:809]: I'm not sure but I think this block should be placed outer of `if split.size == 1 && original_bytesize == 0` block because probably this case can be occurred also on `split.size != 1` or `original_bytesize != 0`.

```diff
diff --git a/lib/fluent/plugin/buffer.rb b/lib/fluent/plugin/buffer.rb
index 7275d70c..f113f06b 100644
--- a/lib/fluent/plugin/buffer.rb
+++ b/lib/fluent/plugin/buffer.rb
@@ -804,24 +804,23 @@ module Fluent
                 if chunk_size_over?(chunk) # split size is larger than difference between size_full? and size_over?
                   chunk.rollback
                   committed_bytesize = chunk.bytesize
-                  if split.size == 1 && original_bytesize == 0
-                    if adding_bytes < @chunk_limit_size
-                      # As already processed content is kept after rollback, then unstaged chunk should be queued.
-                      # After that, re-process current split again.
-                      # New chunk should be allocated, to do it, modify @stage and so on.
-                      synchronize { @stage.delete(modified_metadata) }
-                      staged_chunk_used = false
-                      chunk.unstaged!
-                      break
-                    else
-                      # It is obviously case that BufferChunkOverflowError should be raised here,
-                      # but if it raises here, already processed 'split' or
-                      # the proceeding 'split' will be lost completely.
-                      # so it is a last resort to delay raising such a exception
-                      errors << "concatenated/appended a #{adding_bytes} bytes record (nth: #{writing_splits_index}) is larger than buffer chunk limit size (#{@chunk_limit_size})"
-                      writing_splits_index += 1
-                      next
-                    end
+                  if split.size == 1 && adding_bytes > @chunk_limit_size
+                    # It is obviously case that BufferChunkOverflowError should be raised here,
+                    # but if it raises here, already processed 'split' or
+                    # the proceeding 'split' will be lost completely.
+                    # so it is a last resort to delay raising such a exception
+                    errors << "concatenated/appended a #{adding_bytes} bytes record (nth: #{writing_splits_index}) is larger than buffer chunk limit size (#{@chunk_limit_size})"
+                    writing_splits_index += 1
+                    next
+                  end
+                  if adding_bytes < @chunk_limit_size
+                    # As already processed content is kept after rollback, then unstaged chunk should be queued.
+                    # After that, re-process current split again.
+                    # New chunk should be allocated, to do it, modify @stage and so on.
+                    synchronize { @stage.delete(modified_metadata) }
+                    staged_chunk_used = false
+                    chunk.unstaged!
+                    break
                   end
 
                   if chunk_size_full?(chunk) || split.size == 1
```

In addition, note that above patch includes the following change for detecting 1 big record:

```diff
- if split.size == 1 && original_bytesize == 0
+ if split.size == 1 && adding_bytes > @chunk_limit_size
```

I think it's more proper way to detect it.
(Without it, newly added tests are failed.)

Comment (ashie) [reply lib/fluent/plugin/buffer.rb:809]: > because probably this case can be occurred also on `split.size != 1` or `original_bytesize != 0`.

Hmm, probably I was wrong. It seems that it doesn't occur when `split.size != 1`.

Comment (ashie) [reply lib/fluent/plugin/buffer.rb:821]: I made it more understandable (for me...)

**Review by ashie — APPROVED** [review]

**Comment by ashie** [comment]
Waiting CI...

File: lib/fluent/plugin/buffer.rb [hunk 3]
```diff
@@ -793,19 +806,26 @@ def write_step_by_step(metadata, data, format, splits_count, &block)
...
+                      writing_splits_index += 1
+                      next
+                    else
+                      # As already processed content is kept after rollback, then unstaged chunk should be queued.
+                      # After that, re-process current split again.
+                      # New chunk should be allocated, to do it, modify @stage and so on.
+                      synchronize { @stage.delete(modified_metadata) }
+                      staged_chunk_used = false
+                      chunk.unstaged!
+                      break
```
Comment (daipom) [inline lib/fluent/plugin/buffer.rb:827]: Why does this unstage the current chunk?
