### PR TITLE
parser_json: Add stream_buffer_size config param

### LINKED ISSUE #609: in_exec json streams does not work as expected
ruby-yajl reads 8k from the input stream before parsing so input is delayed until the buffer is full (which can take forever if no new input is generated).

This can be reproduced with the following config:

    <source>
      type exec
      format tsv
      command while sleep 1; do date; done
      keys tsv_date
      tag all
    </source>

    <source>
      type exec
      format json
      command while sleep 1; do echo '{"json_date": "'$(date)'"}'; done
      tag all
    </source>

    <match all>
      type stdout
    </match>

tsv_date is emitted each time but json_date is not emitted until the buffer is full (~5 minutes in this case).

I have created a workaround https://github.com/serbaut/fluentd/commit/c99bcf47a3695cd39aa211ccb2b0bd8bac5a704c that parses line by line but in the end ruby-yajl has to be fixed so is parses one json document at a time.

### PR DESCRIPTION
**Pull request by benwh**
**Which issue(s) this PR fixes**: 
Fixes #609 

**What this PR does / why we need it**: 
Allow configuration of the size of the buffer that Yajl uses when parsing streaming input.

The advantage of this is that when using `out_exec_filter`, and parsing
as JSON, it's now possible to configure this plugin to avoid having to
wait for 8192 bytes of data to be parsed before events are emitted.

**Docs Changes**: fluent/fluentd-docs#631

**Release Note**: 
Use PR title.

### CODE REVIEW

File: lib/fluent/plugin/out_exec_filter.rb [hunk 1]
```diff
@@ -95,6 +95,7 @@ class ExecFilterOutput < Output
     COMPAT_PARSE_PARAMS = {
       'out_format' => '@type',
       'out_keys' => 'keys',
+      'out_stream_buffer_size' => 'stream_buffer_size',
```
Comment (benwh) [inline lib/fluent/plugin/out_exec_filter.rb]: The only reason that this was added was to shave another 30s off the tests

File: test/plugin/test_parser_json.rb [hunk 2]
```diff
@@ -111,4 +111,29 @@ def test_parse_with_keep_time_key_without_time_format(data)
       assert_equal text, record['time']
     end
   end
+
+  data('yajl' => 'yajl')
+  def test_yajl_parse_io_with_buffer_smaller_than_input(data)
```
Comment (benwh) [inline test/plugin/test_parser_json.rb]: I was considering adding a test case for the inverse of this (input smaller than buffer) but didn't do this because it seemed like it would be quite awkward to implement - due to needing to assert on the parser *not* emitting an event - and probably not provide much value.
Happy to reconsider this if anyone has a suggestion on how this could be done neatly though!

File: lib/fluent/plugin/parser_json.rb [hunk 3]
```diff
@@ -30,6 +30,11 @@ class JSONParser < Parser
       desc 'Set JSON parser'
       config_param :json_parser, :enum, list: [:oj, :yajl, :json], default: :oj
 
+      # The Yajl library defines a default buffer size of 8092 when parsing
+      # from IO streams, so maintain this for backwards-compatibility.
+      # https://www.rubydoc.info/github/brianmario/yajl-ruby/Yajl%2FParser:parse
+      config_param :stream_buffer_size, :integer, default: 8092
```
Comment (repeatedly) [inline lib/fluent/plugin/parser_json.rb]: Please add `:desc` parameter to explain the parameter.  This is only for `yajl`.

File: test/plugin/test_parser_json.rb [hunk 4]
```diff
@@ -111,4 +111,29 @@ def test_parse_with_keep_time_key_without_time_format(data)
       assert_equal text, record['time']
     end
   end
+
+  data('yajl' => 'yajl')
```
Comment (repeatedly) [inline test/plugin/test_parser_json.rb]: Don't use `data` for only 1 pattern.

File: lib/fluent/plugin/parser_json.rb (hunk 3 above)
Comment (benwh) [reply lib/fluent/plugin/parser_json.rb]: Done!

File: test/plugin/test_parser_json.rb (hunk 4 above)
Comment (benwh) [reply test/plugin/test_parser_json.rb]: Good point, sorted :)

**Comment by benwh** [comment]
Hi @repeatedly, those issues are fixed so could you take another look when you get some time? Thanks!

File: lib/fluent/plugin/parser_json.rb (hunk 3 above)
Comment (repeatedly) [reply lib/fluent/plugin/parser_json.rb]: If you use `desc` method, not `:desc` parameter, it should be put on top of `config_param`.
Currently, `desc 'Set the buffer size that Yajl will use when parsing streaming input'` is for `time_tupe`, not `stream_buffer_size`.
See https://docs.fluentd.org/v1.0/articles/api-plugin-base

Comment (benwh) [reply lib/fluent/plugin/parser_json.rb]: Ah, that was a silly mistake, thanks for the pointer! Fixed.

File: lib/fluent/plugin/parser_json.rb [hunk 5]
```diff
@@ -30,6 +30,12 @@ class JSONParser < Parser
       desc 'Set JSON parser'
       config_param :json_parser, :enum, list: [:oj, :yajl, :json], default: :oj
 
+      # The Yajl library defines a default buffer size of 8092 when parsing
```
Comment (ganmacs) [inline lib/fluent/plugin/parser_json.rb]: [nits] It may be better a default buffer size is 8192  because of https://github.com/brianmario/yajl-ruby/commit/9d4cca0175142c2308746d7c1d40d89b682b168f

File: test/plugin/test_parser_json.rb [hunk 6]
```diff
@@ -111,4 +111,28 @@ def test_parse_with_keep_time_key_without_time_format(data)
...
+  def test_yajl_parse_io_with_buffer_smaller_than_input
+    parser = Fluent::Test::Driver::Parser.new(Fluent::Plugin::JSONParser)
+    parser.configure(
+                     'keep_time_key' => 'true',
+                     'json_parser' => 'yajl',
+                     'stream_buffer_size' => 1,
+                     )
+    text = "100"
+
+    waiting(5) do
```
Comment (ganmacs) [inline test/plugin/test_parser_json.rb]: Does it need? this test suit seems not to block since L134.

File: lib/fluent/plugin/parser_json.rb (hunk 5 above)
Comment (ganmacs) [reply lib/fluent/plugin/parser_json.rb]: FYI: https://github.com/brianmario/yajl-ruby/pull/192

Comment (benwh) [reply lib/fluent/plugin/parser_json.rb]: Definitely not a nit; thanks for picking up on this! I did think that 8092 bytes was a bit of a strange size for a buffer, but didn't look into it 🤦‍♂️. 
Fixed and I'll update the docs PR too.

File: test/plugin/test_parser_json.rb (hunk 6 above)
Comment (benwh) [reply test/plugin/test_parser_json.rb]: Yes it's not actually required for the test to work, I put it there to protect against any regression in the code being tested (or the test scaffolding) that might cause the test to fail, because if it does then it will block forever which would be quite annoying when it runs in CI, if nothing else.

**Comment by repeatedly** [comment]
Thx!
