### PR TITLE
Propagate default value change from subclass of compat plugins

### LINKED ISSUE #995: fluent-plugin-webhdfs fails test with fluentd v0.14.0.rc.3
### How to reproduce

```
$ git clone git@github.com:fluent/fluent-plugin-webhdfs.git
$ cd fluent-plugin-webhdfs
$ echo 'gem "fluentd", "=0.14.0.rc.3"' >> Gemfile
$ bundle install
$ bundle exec rake test
```

### Result

Some test fails  as below.

```
Error: test_default(WebHDFSOutputTest::ConfigureTest::PathFormatTest): Fluent::ConfigError: 'path' parameter is required
fluentd/lib/fluent/config/section.rb:140:in `block in generate'
fluentd/lib/fluent/config/section.rb:127:in `each_pair'
fluentd/lib/fluent/config/section.rb:127:in `generate'
fluentd/lib/fluent/configurable.rb:68:in `configure'
fluentd/lib/fluent/plugin/base.rb:39:in `configure'
fluentd/lib/fluent/plugin/buffer.rb:86:in `configure'
fluentd/lib/fluent/plugin/buf_file.rb:57:in `configure'
fluentd/lib/fluent/plugin/output.rb:267:in `configure'
fluentd/lib/fluent/plugin_helper/event_emitter.rb:60:in `configure'
fluentd/lib/fluent/compat/output.rb:578:in `configure'
2.3.0/lib/ruby/gems/2.3.0/gems/fluent-mixin-config-placeholders-0.3.1/lib/fluent/mixin/config_placeholders.rb:106:in `configure'
2.3.0/lib/ruby/gems/2.3.0/gems/fluent-mixin-plaintextformatter-0.2.6/lib/fluent/mixin/plaintextformatter.rb:21:in `configure'
fluent-plugin-webhdfs/lib/fluent/plugin/out_webhdfs.rb:126:in `configure'
fluentd/lib/fluent/test/base.rb:71:in `configure'
fluent-plugin-webhdfs/test/plugin/test_out_webhdfs.rb:13:in `create_driver'
fluent-plugin-webhdfs/test/plugin/test_out_webhdfs.rb:100:in `test_default'
      97:
      98:     class PathFormatTest < self
      99:       def test_default
  => 100:         d = create_driver
     101:         assert_equal '/hdfs/path/file.%Y%m%d.log', d.instance.path
     102:         assert_equal '%Y%m%d', d.instance.time_slice_format
     103:         assert_equal '/hdfs/path/file.20120718.log', d.instance.path_format('20120718')
```

`path` parameter is not required in plugin definition.

I think something wrong around https://github.com/fluent/fluentd/blob/master/lib/fluent/config/section.rb#L140

### PR DESCRIPTION
**Pull request by tagomoris**
3rd party plugins with v0.12 APIs may change default values of parameters, which is controlled by compat layers. This change should be propagated to defaults of `<buffer>` section.
This change fixes #995.

### CODE REVIEW

File: lib/fluent/compat/propagate_default.rb [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+
+        def config_set_default(name, defval)
+          CONFIGURABLE_CLASS_METHODS.instance_method(:config_set_default).bind(self).call(name, defval)
+          pparams = propagate_default_params
+          if pparams[name.to_s]
+            newer = pparams[name.to_s].to_sym
+
+            CONFIGURABLE_CLASS_METHODS.instance_method(:config_section).bind(self).call(:buffer) do
+              self.config_set_default newer, defval
+              p(name: name, newer: newer, defval: defval, defaults: self.defaults)
```
Comment (repeatedly) [inline lib/fluent/compat/propagate_default.rb]: What does this `p`?

Comment (tagomoris) [inline lib/fluent/compat/propagate_default.rb]: Ahhhhhhh

Comment (tagomoris) [inline lib/fluent/compat/propagate_default.rb]: pushed a commit to remove these debug print.
