### PR TITLE
in_tail: Ensure to detach correct watcher on rotation with follow_inodes

### LINKED ISSUE #3614: Fluentd in_tail "unreadable" file causes "following tail of <file>" to stop and no logs pushed
### Describe the bug

After a warning of an "unreadable" (likely due to rotation), no more logs were pushed (in_tail + pos_file).
Reloading config or restarting fluentd sorts the issue.
All other existing files being tracked continued to work as expected.

### To Reproduce

Not able to reproduce at will.

### Expected behavior

Logs to be pushed as usual after file rotation as fluentd recovers from the temporary "unreadable" file.

### Your Environment

```markdown
- Fluentd version: 1.14.4
- TD Agent version: 4.2.0
- Operating system: Ubuntu 20.04.3 LTS
- Kernel version: 5.11.0-1022-aws
```

### Your Configuration

```apache
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/es-containers.log.pos
  tag kubernetes.*
  <parse>
    @type regexp
    expression /^(?<time>[^ ]+) (?<stream>[^ ]+) (?<logtag>[^ ]+) (?<log>.+)$/
    time_key time
    time_format %Y-%m-%dT%H:%M:%S.%N%z
  </parse>
  read_from_head true
</source>
```

### Your Error Log

```shell
Relevant log entries with some context. When "detected rotation of ..." isn't followed by a "following tail of ..." then log file contents aren't being processed/pushed:

2022-02-01 01:26:33 +0000 [info]: #0 detected rotation of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log; waiting 5 seconds
2022-02-01 01:26:33 +0000 [info]: #0 following tail of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log
2022-02-01 01:32:53 +0000 [warn]: #0 /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log unreadable. It is excluded and would be examined next time.
2022-02-01 01:32:54 +0000 [info]: #0 detected rotation of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log; waiting 5 seconds
2022-02-01 01:32:54 +0000 [info]: #0 following tail of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log
2022-02-01 01:38:04 +0000 [info]: #0 detected rotation of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log; waiting 5 seconds
2022-02-01 01:44:44 +0000 [info]: #0 detected rotation of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log; waiting 5 seconds
2022-02-01 01:53:15 +0000 [info]: #0 detected rotation of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log; waiting 5 seconds
[...]
---- after issuing a config reload (kill -SIGUSR2 <pid>) it starts to work fine again, i.e. "following tail of ..." 
2022-02-01 11:36:19 +0000 [info]: Reloading new config
2022-02-01 11:36:19 +0000 [info]: using configuration file: <ROOT>
[...]
2022-02-01 11:36:19 +0000 [info]: shutting down input plugin type=:tail plugin_id="object:c6c0"
[...]
2022-02-01 11:36:19 +0000 [info]: adding source type="tail"
2022-02-01 11:36:19 +0000 [info]: #0 shutting down fluentd worker worker=0
2022-02-01 11:36:19 +0000 [info]: #0 shutting down input plugin type=:tail plugin_id="object:c6c0"
[...]
2022-02-01 11:36:20 +0000 [info]: #0 restart fluentd worker worker=0
---- the entry below seems to be related with the actual underlying issue... the ruby object which stopped pushing logs has now been terminated as a new one was created
2022-02-01 11:36:20 +0000 [warn]: #0 /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log already exists. use latest one: deleted #<struct Fluent::Plugin::TailInput::Entry path="/var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log", pos=10740032, ino=1797715, seek=1530>
2022-02-01 11:36:20 +0000 [info]: #0 following tail of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log
2022-02-01 11:37:30 +0000 [info]: #0 detected rotation of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log; waiting 5 seconds
2022-02-01 11:37:30 +0000 [info]: #0 following tail of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log
2022-02-01 11:43:20 +0000 [info]: #0 detected rotation of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log; waiting 5 seconds
2022-02-01 11:43:20 +0000 [info]: #0 following tail of /var/log/containers/gateway-mtcw6_atom_pcms-gateway-e54ea9ee115f1127682b0d92e37404e4b1693c14edeea93e485f70b3110eecfc.log
```

### Additional context

This issue seems be related with #3586 but unfortunately I didn't check the `pos` file while the issue was happening so can't tell if it presented unexpected values for the failing file.

### PR DESCRIPTION
**Pull request by daipom**
**Which issue(s) this PR fixes**: 
* Partially fixes #3614

**What this PR does / why we need it**: 
If `refresh_watchers` run before `update_watcher`, the old implementation of `update_watcher` detach wrongly the new TailWatcher which is added in `refresh_watcher`. This causes the problem of stopping tailing log and handle leak.

The test case `test_updateTW_after_refreshTW` reproduces this problem.
This PR solves it.

NOTE: There is another BUG about unwatching. (I adjusted some expected values of the tests for this BUG.)
When `refresh_watcher` find the rotated old file AFTER unwatching it (`rotate_wait`), then the logs will be collected in duplicate.
If `refresh_watcher` find it BEFORE unwatching it (`rotate_wait`), this problem doesn't occur because the position entry is still alive.
We need to fix this and fix the adjusted expected values.

**Docs Changes**:
Not needed.

**Release Note**: 
Same as the title.

**OTHERS**:
This fix is based on the content and discussion of the following issue and PR:

* #3614
* #4185
* #4191

Thanks to those who have given me much insight, especially @kattz-kawa, @masaki-hatada, and @garyzjq!

### CODE REVIEW

**Comment by daipom** [comment]
The scenario of this problem (basically from https://github.com/fluent/fluentd/pull/4185#issuecomment-1580772174)
Please refer to the test case `test_updateTW_after_refreshTW`.

When `follow_inodes` is enabled.

* Files: `file.log (inode-A)`
  * `@tails[file.log]` => `Watcher(file.log, inode-A)`
* Rotation!
  * file.log is moved to file.log.1.
  * A new file is created as file.log.
* Files: `file.log (inode-B)`, `file.log.1 (inode-A)`
* `refresh_watcher` and `update_watcher` can be processed at the same time...

If `refresh_watcher` is processed before `update_watcher`
1. `refresh_watcher`
   * Find `file.log (inode-B)` as a new target.
   * **OVERWRITE** `@tails[file.log]` by `Watcher(file.log, inode-B)`
     * `@tails[file.log]` already has a watcher. We can't overwrite it here.
   * Result:
     * `@tails[file.log]` => `Watcher(file.log, inode-B)`
     * `Watcher(file.log, inode-A)` remains, but it does **NOT EXIST** in `@tails`.
       * This was causing handle leaks.
1. `update_watcher`
   * `Watcher(file.log, inode-A)` will call it's `update_watcher`
     * This will update the inode of file.log to inode-B.
     * Old implementation
       * Detach `@tails[file.log]` (`Watcher(file.log, inode-B)`) **WRONG**
         * This stops tailing the new file!!
     * This PR
       * Detach self (`Watcher(file.log, inode-A)`). **CORRECT**
       * This solves the problem both of stopping tailing and handle leaks.

File: lib/fluent/plugin/in_tail.rb [hunk 1]
```diff
@@ -499,23 +499,26 @@ def update_watcher(target_info, pe)
         end
       end
 
-      rotated_tw = @tails[path]
```
Comment (daipom) [inline lib/fluent/plugin/in_tail.rb:502]: NOTE: `@tails[path]` should point to the caller of this function ( = self-watcher).
So I pass self-watcher directly to this function.

This way, we can avoid the impact of `refresh_watcher` being executed first and `@tails` being overwritten.

Comment (masaki-hatada) [reply lib/fluent/plugin/in_tail.rb:502]: > NOTE: @tails[path] should point to the caller of this function ( = self-watcher).
> So I pass self-watcher directly to this function.

Maybe this is a good idea to prevent closing a new watcher wrongly.
Currently I'm checking this patch as code level and @kattz-kawa is evaluating this patch on our env.

File: lib/fluent/plugin/in_tail.rb [hunk 2]
```diff
@@ -484,8 +484,8 @@ def close_watcher_handles
     end
 
     # refresh_watchers calls @tails.keys so we don't use stop_watcher -> start_watcher sequence for safety.
-    def update_watcher(target_info, pe)
-      path = target_info.path
+    def update_watcher(watcher, pe, new_inode)
```
Comment (ashie) [inline lib/fluent/plugin/in_tail.rb:487]: nit: I prefer tail_watcher for the first argument.
```suggestion
    def update_watcher(tail_watcher, pe, new_inode)
```
In this plugin various type of `watcher`s are appeared so that `watcher`  is confusing.

Probably there are 3 local variable names to represent it in this plugin:

1. `tw`
2. `watcher`
3. `tail_watcher`

1. is also acceptable for me.
Although it's too short but not so confusing in this context, and it's appeared most often in this code.

Comment (daipom) [reply lib/fluent/plugin/in_tail.rb:487]: Thanks for your review! I see!
Should we change the method name too?

```diff
- update_watcher(watcher, pe, new_inode)
+ update_tail_watcher(tail_watcher, pe, new_inode)
```

Comment (daipom) [reply lib/fluent/plugin/in_tail.rb]: Fixed!
I used `tail_watcher`!

**Comment by kattz-kawa** [comment]
Hi @daipom

Thank you for the disuccsing regarding #3614. 
And I appreciate the adding co-authored sign on this PR's commit message.

@masaki-hatada and Me have checked and tested heavily last week.
It looks good.
There is no concern for us.
I hope that this PR merged in the future release for fixing incorrect file handle issue.

**Review by masaki-hatada — APPROVED** [review]
Looks good for me.

File: lib/fluent/plugin/in_tail.rb (hunk 1 above)
Comment (ashie) [reply lib/fluent/plugin/in_tail.rb:502]: I agree with your idea too.

File: test/plugin/test_in_tail.rb [hunk 3]
```diff
@@ -2638,4 +2638,278 @@ def test_lines_collected_with_no_throttling(data)
...
+      Fluent::FileWrapper.open("#{@tmp_dir}/tail.pos", "r") do |f|
+        f.readlines(chomp: true).each do |line|
+          values = line.split("\t")
+          position_entries.append([values[0], values[1], values[2].to_i(16)])
+        end
+      end
+
+      assert_equal(
+        {
+          # TODO: This is BUG!! We need to fix it and replace this with the next.
```
Comment (ashie) [inline test/plugin/test_in_tail.rb:2708]: :thinking:

File: test/plugin/test_in_tail.rb [hunk 4]
```diff
@@ -2638,4 +2638,278 @@ def test_lines_collected_with_no_throttling(data)
       end
     end
   end
+
+  # https://github.com/fluent/fluentd/issues/3614
```
Comment (ashie) [inline test/plugin/test_in_tail.rb:2642]: It prefer #4190 instead of #3614 here to clarify the mechanism of this bug.

File: test/plugin/test_in_tail.rb [hunk 5]
```diff
@@ -2638,4 +2638,278 @@ def test_lines_collected_with_no_throttling(data)
...
+          record_values: record_values,
+          tail_watcher_paths: tail_watchers.collect { |tw| tw.path },
+          tail_watcher_inodes: tail_watchers.collect { |tw| tw.ino },
+          tail_watcher_io_handler_opened_statuses: tail_watchers.collect { |tw| tw.instance_variable_get(:@io_handler)&.opened? || false },
+          position_entries: position_entries
+        },
+      )
+    end
+
+    def test_updateTW_after_refreshTW
```
Comment (ashie) [inline test/plugin/test_in_tail.rb:2820]: This is the case described in #4190, isn't it?
Can you add something a mark to distinguish it?
It's okay for me that Just moving the comment at the head of `sub_test_case` (`# https://github.com/fluent/fluentd/issues/3614`) to here.

File: test/plugin/test_in_tail.rb (hunk 3 above)
Comment (ashie) [reply test/plugin/test_in_tail.rb:2708]: It's not intended usage, rotated files should be excluded by `path` parameter although they are included in this test (`#{@tmp_dir}/tail.txt*`).

**Comment by daipom** [comment]
@kattz-kawa @masaki-hatada Thanks for your review!

**Comment by daipom** [comment]
@ashie Thanks for your review! I'll check it.

File: test/plugin/test_in_tail.rb (hunk 3 above)
Comment (ashie) [reply test/plugin/test_in_tail.rb:2708]: It's hard to detect whether tail.txt1 is a completely new file or rotated file, since same inode with a different path is possible especially on just after deleting a file (since a newly created file is often given a same inode with the file delete just before it).
So I think we don't need to care rotated files by our code, they should be excluded by the `path` pattern.

So the test code should exclude the rotated path pattern.

Comment (ashie) [reply test/plugin/test_in_tail.rb:2708]: ... :thinking:（That should not be.)
Sorry, probably it's my misunderstanding.
Please ignore my comment.

Comment (daipom) [reply test/plugin/test_in_tail.rb:2708]: Since the position is erased during [unwatch](https://github.com/fluent/fluentd/blob/b71ab139b25bfcb8cb3df87385a7f94c8f6fd220/lib/fluent/plugin/in_tail/position_file.rb#L56-L60), there is a possibility of collecting duplicate files after the rotation depending on timing.

This is for reducing memory consumption:

* #2803

However, it does not seem to work correctly with `follow_inodes`, which is implemented after this fix.

I want to fix it following this PR.

**Review by ashie — APPROVED** [review]
LGTM (above my comments are nitpicking)

File: test/plugin/test_in_tail.rb (hunk 5 above)
Comment (daipom) [reply test/plugin/test_in_tail.rb:2821]: Thanks! I see!
I moved that comment here and fix it to #4190.

File: test/plugin/test_in_tail.rb (hunk 4 above)
Comment (daipom) [reply test/plugin/test_in_tail.rb]: Thanks! I see!
Fixed in https://github.com/fluent/fluentd/pull/4208#discussion_r1241854041.

**Comment by ashie** [comment]
Thanks to all contributors who help investigating this issue!

**Comment by ashie** [comment]
TODO:
* Apply it to v1.16 branch
* How about `follow_inode false`?

**Comment by daipom** [comment]
Thanks to all contributors who have given me much insight, especially @kattz-kawa, @masaki-hatada, and @garyzjq!
And thanks for your review!
