### PR TITLE
server helper: Fix IPv6 dual stack mode issue for tcp socket.

### LINKED ISSUE #2682: When using the same port number, the td-agent fails to bind to IPv4 alongside IPv6
**Describe the bug**
When trying to configure the td-agent to bind both to IPv4 and IPv6 using the same port, The following error occurs: 
```
2019-11-04 14:00:26 +0000 [error]: #0 unexpected error error_class=Errno::EADDRINUSE error="Address already in use - bind(2) for \"0.0.0.0\" port 8888"
```
**To Reproduce**
Use the below-mentioned configuration.

**Expected behavior**
fluentd should be able to use the same port number for both types of IP addresses.

**Your Environment**

- Fluentd or td-agent version: `td-agent 1.7.4`
- Operating system: `Fedora 29`
- Kernel version: `4.18.16-300.fc29.x86_64`

**Your Configuration**
```
<source>
  @type http
  @id input_http_ipv4
  port 8888
</source>

<source>
  @type http
  @id input_http_ipv6
  bind ::
  port 8888
</source>

<match *.*>
  @type stdout
</match>```
```
**Your Error Log**

```
2019-11-04 14:00:26 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.5'
2019-11-04 14:00:26 +0000 [info]: gem 'fluent-plugin-kafka' version '0.12.1'
2019-11-04 14:00:26 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.7.0'
2019-11-04 14:00:26 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-11-04 14:00:26 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2019-11-04 14:00:26 +0000 [info]: gem 'fluent-plugin-s3' version '1.2.0'
2019-11-04 14:00:26 +0000 [info]: gem 'fluent-plugin-td' version '1.0.0'
2019-11-04 14:00:26 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2019-11-04 14:00:26 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.4'
2019-11-04 14:00:26 +0000 [info]: gem 'fluentd' version '1.7.4'
2019-11-04 14:00:26 +0000 [info]: adding match pattern="*.*" type="stdout"
2019-11-04 14:00:26 +0000 [info]: adding source type="http"
2019-11-04 14:00:26 +0000 [info]: adding source type="http"
2019-11-04 14:00:26 +0000 [info]: #0 starting fluentd worker pid=5959 ppid=5930 worker=0
2019-11-04 14:00:26 +0000 [error]: #0 unexpected error error_class=Errno::EADDRINUSE error="Address already in use - bind(2) for \"0.0.0.0\" port 8888"
  2019-11-04 14:00:26 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.1.1/lib/serverengine/socket_manager_unix.rb:53:in `initialize'
  2019-11-04 14:00:26 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.1.1/lib/serverengine/socket_manager_unix.rb:53:in `new'
  2019-11-04 14:00:26 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.1.1/lib/serverengine/socket_manager_unix.rb:53:in `listen_tcp_new'
  2019-11-04 14:00:26 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.1.1/lib/serverengine/socket_manager.rb:121:in `block in listen'
  2019-11-04 14:00:26 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.1.1/lib/serverengine/socket_manager.rb:119:in `synchronize'
  2019-11-04 14:00:26 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.1.1/lib/serverengine/socket_manager.rb:119:in `listen'
  2019-11-04 14:00:26 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.1.1/lib/serverengine/socket_manager.rb:128:in `listen_tcp'
  2019-11-04 14:00:26 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.1.1/lib/serverengine/socket_manager_unix.rb:106:in `send_socket'
  2019-11-04 14:00:26 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/serverengine-2.1.1/lib/serverengine/socket_manager.rb:155:in `process_peer'
2019-11-04 14:00:26 +0000 [error]: #0 unexpected error error_class=Errno::EADDRINUSE error="Address already in use - bind(2) for \"0.0.0.0\" port 8888"
  2019-11-04 14:00:26 +0000 [error]: #0 suppressed same stacktrace
```

**Additional context**

Just to note that as a workaround, if you set two different port numbers, it binds to both IPv4 and IPv6.
```
netstat -ntpl | grep ruby
tcp        0      0 0.0.0.0:48888           0.0.0.0:*               LISTEN      6152/ruby
tcp6       0      0 :::8888                 :::*                    LISTEN      6152/ruby
```

### PR DESCRIPTION
**Pull request by repeatedly**
Signed-off-by: Masahiro Nakagawa <repeatedly@gmail.com>

**Which issue(s) this PR fixes**: 
Fixes #2682 

**What this PR does / why we need it**: 
Use other socket method to set `IPV6_V6ONLY`.
See also https://github.com/treasure-data/serverengine/pull/101

**Docs Changes**:
No need

**Release Note**: 
Same as title

### CODE REVIEW

**Comment by ganmacs** [comment]
Don't you add a test for this?

**Comment by repeatedly** [comment]
Just added test.

File: lib/fluent/plugin_helper/server.rb [hunk 1]
```diff
@@ -355,7 +355,11 @@ def server_create_tcp_socket(shared, bind, port)
         sock = if shared
                  server_socket_manager_client.listen_tcp(bind, port)
                else
-                 TCPServer.new(bind, port) # this method call can create sockets for AF_INET6
+                 # TCPServer.new doesn't set IPV6_V6ONLY flag, so use Addrinfo class instead.
+                 # backlog will be set correctly so use listen's default here
```
Comment (ganmacs) [inline lib/fluent/plugin_helper/server.rb]: > backlog will be set correctly

What does this mean?  who sets backlog?

Comment (repeatedly) [reply lib/fluent/plugin_helper/server.rb]: `server_create_tcp_socket` is used in other API, e.g. server_create, so it sets backlog from plugins.

Comment (ganmacs) [reply lib/fluent/plugin_helper/server.rb]: This one? https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin_helper/server.rb#L222
How about "backlog will be set by the caller, we don't set backlog here", then? (it's IMO. so it's ok for me to leave as it is)
