### PR TITLE
out_http: TLS1.3 support

### LINKED ISSUE #4332: TLS 1.3 support in http output plugin
### Discussed in https://github.com/fluent/fluentd/discussions/4329

<div type='discussions-op-text'>

<sup>Originally posted by **mikakatua** October 22, 2023</sup>
I'm trying to use fluentd to send logs to a http endpoint. This endpoint only supports TLS 1.3

My configuration is as follows:
```
<source>
  @type forward
  @label @mainstream
  port 24224
  bind 0.0.0.0
</source>

<label @mainstream>
  <match **>
    @type http
    endpoint https://haproxy:8443/data/logs
    tls_verify_mode none
    tls_version TLSv1_3
    <format>
      @type json
    </format>
    json_array true
    <buffer>
      flush_interval 2s
    </buffer>
  </match>
</label>
```
This does not work. I get the error:
> [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="unknown SSL method `TLSv1_3'"

Looking at the [http output documentation](https://docs.fluentd.org/output/http#tls_version) it looks like the max version is TLS 1.2. I have verified that it works removing the `tls_version` parameter and downgrading the ssl configuration of the endpoint to support TLS 1.2.

If I remove the `tls_version` parameter without downgrading the endpoint, the error is:
> [warn]: #0 failed to flush the buffer. retry_times=0 next_retry_time=2023-10-21 15:55:12 +0000 chunk="6083c037d2f85b70a8f464156a75b22d" error_class=OpenSSL::SSL::SSLError error="SSL_connect returned=1 errno=0 peeraddr=172.18.0.4:8443 state=error: tlsv1 alert protocol version"

Is there any way to get it working with TLS 1.3?

I'm using Fluentd v1.16.2-1.0 docker image</div>

### PR DESCRIPTION
**Pull request by Athishpranav2003**
**Which issue(s) this PR fixes**: 
Fixes #4332 

**What this PR does / why we need it**: 
Changes the way we configure Net::HTTP client.

**Docs Changes**:
https://github.com/fluent/fluentd-docs-gitbook/pull/579

**Release Note**: 
The same as the title.

### CODE REVIEW

**Comment by Athishpranav2003** [comment]
@daipom ignore the test fails for now. I guess that is wrt to webrick issue.

**Comment by daipom** [comment]
@Athishpranav2003 This PR is in draft status. Please let me know if there are any TODO.

**Comment by daipom** [comment]
OK! Thanks!

File: lib/fluent/tls.rb [hunk 1]
```diff
@@ -48,7 +48,7 @@ module TLS
                     MIN_MAX_AVAILABLE = false
                     map
                   end
-    private_constant :METHODS_MAP
+    # private_constant :METHODS_MAP
```
Comment (kenhys) [inline lib/fluent/tls.rb:51]: Instead of publishing private, it might be better to provide min / max accessor

**Comment by Athishpranav2003** [comment]
Hey guys

i am back, was busy with college. Will look at this pr this week

**Comment by Athishpranav2003** [comment]
Testing output
```
2025-05-17 17:23:47 +0530 [info]: fluent/log.rb:362:: using configuration file: <ROOT>
  <source>
    @type sample
    @label @mainstream
    sample {"hello1":"world","foo1":"bar"}
    tag "sample"
  </source>
  <label @mainstream>
    <match **>
      @type http
      endpoint "https://0.0.0.0:8000"
      tls_verify_mode none
      tls_version TLSv1_3
      json_array true
      <format>
        @type "json"
      </format>
      <buffer>
        flush_interval 2s
      </buffer>
    </match>
  </label>
</ROOT>
2025-05-17 17:23:47 +0530 [info]: fluent/log.rb:362:: starting fluentd-1.18.0 pid=41729 ruby="3.4.2"
2025-05-17 17:23:47 +0530 [info]: fluent/log.rb:362:: spawn command to main:  cmdline=["/usr/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/sbin/fluentd", "-c", "fluentd.conf", "-v", "--under-supervisor"]
2025-05-17 17:23:48 +0530 [info]: #0 fluent/log.rb:362:: fluentd worker is now running worker=0
2025-05-17 17:23:48 +0530 [debug]: #0 fluent/log.rb:341:: flush_thread actually running
2025-05-17 17:23:48 +0530 [debug]: #0 fluent/log.rb:341:: enqueue_thread actually running
2025-05-17 17:23:52 +0530 [debug]: #0 fluent/log.rb:341:: Post data to https://0.0.0.0:8000 with chunk(635538d474b42c0c20451f2461610d3e)
```

@daipom

File: lib/fluent/tls.rb (hunk 1 above)
Comment (Athishpranav2003) [reply lib/fluent/tls.rb:51]: Hey,

i included a seperate accessor to set the `Net::HTTP` options

**Comment by daipom** [comment]
Thanks! We will see this soon!

File: lib/fluent/tls.rb [hunk 2]
```diff
@@ -75,7 +75,31 @@ def set_version_to_context(ctx, version, min_version, max_version)
...
+        end
+        opt[:min_version] = min_version
+        opt[:max_version] = max_version
+      else
+        opt[:ssl_version] = METHODS_MAP[version] || version
+      end
+
+      opt
+    end
     module_function :set_version_to_context
```
Comment (Watson1978) [inline lib/fluent/tls.rb:101]: I think It would be easier to understand if there is module_function after each method implementation.

**Comment by Watson1978** [comment]
If you rebase your commits with master, It will pass tests on Ruby 3.2 / 3.3 Windows.

File: lib/fluent/tls.rb (hunk 2 above)
Comment (Athishpranav2003) [reply lib/fluent/tls.rb]: Yah,
I placed this line just after the function defintion

**Review by Watson1978 — APPROVED** [review]
👍🏻

**Comment by daipom** [comment]
@Athishpranav2003 Thanks so much for this improvement!

The following would be necessary for us.

* Add some tests to https://github.com/fluent/fluentd/blob/master/test/test_tls.rb
* Update document: https://docs.fluentd.org/output/http#tls_version (https://github.com/fluent/fluentd-docs-gitbook)

@Athishpranav2003
Could you do these if you have time? Especially the addition of tests.
This PR can be merged with TODO to update the document.

**Comment by Athishpranav2003** [comment]
> This PR can be merged with TODO to update the document.

Sure

will do it around this weekend or next week

**Comment by Athishpranav2003** [comment]
@daipom will default tls version stay as tls1.2?

**Comment by daipom** [comment]
@Athishpranav2003 
> will do it around this weekend or next week

Thanks!!

> will default tls version stay as tls1.2?

Yes!
It should be `Fluentd::TLS::DEFAULT_VERSION`:

https://github.com/fluent/fluentd/blob/eeb384e73ea0865fb20020c6b7750799c18165a1/lib/fluent/tls.rb#L22

If we change this, it should be done in a separate PR.
Let's keep the default value as is for now.

**Comment by Athishpranav2003** [comment]
and @daipom what kinda tests to add to test_tls.rb?

**Comment by daipom** [comment]
> and @daipom what kinda tests to add to test_tls.rb?

We want some tests for `Fluent::TLS.set_version_to_options` there.
Every feature of `Fluent::TLS` should be tested in some way here.

We already have tests for `Fluent::TLS.set_version_to_context` here.
Looks like they are very simple tests.
They don't look like enough, but it would be fine to check something like these existing tests.
