### PR TITLE
fix to raise ConfigError for type missing, and its tests

### LINKED ISSUE #1201: Buffer match without type declaration fails with NIL reference
## Environment

- fluentd 0.14.2
- - 
- Ubuntu 16.04

## Configuration

```
# In v1 configuration, type and id are @ prefix parameters.
# @type and @id are recommended. type and id are still available for backward compatibility

## built-in TCP input
## $ echo <json> | fluent-cat <tag>
<source>
  @type forward
  @id forward_input
</source>

# Listen HTTP for monitoring
# http://localhost:24220/api/plugins
# http://localhost:24220/api/plugins?type=TYPE
# http://localhost:24220/api/plugins?tag=MYTAG
<source>
  @type monitor_agent
  @id monitor_agent_input

  port 24220
</source>

# Listen DRb for debug
<source>
  @type debug_agent
  @id debug_agent_input

  bind 127.0.0.1
  port 24230
</source>

## match tag=debug.** and dump to console
<match debug.**>
  @type stdout
  @id stdout_output
</match>
#<source>
#  @type http
#  @id collectd_input
#
#  port 12225
#  format json
#  tag mon.collectd
#</source>

<source>
    @type unix
    @id collectd_input

    path /var/run/collectd-fluentd.sock
    format json
    tag collectd
</source>

<match collectd>
  @type collectd_unroll

  add_tag_prefix mon
</match>

<match mon.*>
  buffer_type file
  buffer_path /var/log/fluent/smc.*.buffer
</match>

<match mon.*>
  @type forward
  send_timeout 60s
  recover_wait 10s
  heartbeat_interval 1s
  phi_threshold 16
  hard_timeout 60s

  <server>
    name fluentd_server
    host fluentd.service
    port 24224
    weight 60
  </server>

  <secondary>
    @type file
    path /var/log/fluent/forward-failed
  </secondary>
</match>
```

Note specifically the presence of the following buffer section, copied almost verbatim from http://docs.fluentd.org/articles/buffer-plugin-overview

```
<match mon.*>
  buffer_type file
  buffer_path /var/log/fluent/smc.*.buffer
</match>
``` 

## Error

When the buffer match is present a NIL reference occurs. If I remove the buffer section, the error disappears.

The error trace:
```
$ fluentd --dry-run -vv
2016-09-01 13:32:48 +0000 [info]: fluent/supervisor.rb:583:read_config: reading config file path="/etc/fluent/fluent.conf"
2016-09-01 13:32:48 +0000 [info]: fluent/supervisor.rb:423:dry_run: starting fluentd-0.14.2 as dry run mode
2016-09-01 13:32:48 +0000 [info]: fluent/engine.rb:116:block in configure: gem 'fluent-plugin-collectd-unroll' version '0.1.1'
2016-09-01 13:32:48 +0000 [info]: fluent/engine.rb:116:block in configure: gem 'fluentd' version '0.14.2'
2016-09-01 13:32:48 +0000 [info]: fluent/engine.rb:116:block in configure: gem 'fluentd' version '0.10.61'
2016-09-01 13:32:48 +0000 [info]: fluent/agent.rb:131:add_match: adding match pattern="debug.**" type="stdout"
2016-09-01 13:32:48 +0000 [trace]: fluent/plugin.rb:140:register_impl: registered output plugin 'stdout'
2016-09-01 13:32:48 +0000 [trace]: fluent/plugin.rb:140:register_impl: registered formatter plugin 'json'
2016-09-01 13:32:48 +0000 [info]: fluent/agent.rb:131:add_match: adding match pattern="collectd" type="collectd_unroll"
2016-09-01 13:32:48 +0000 [trace]: fluent/plugin.rb:140:register_impl: registered output plugin 'collectd_unroll'
2016-09-01 13:32:48 +0000 [info]: fluent/agent.rb:131:add_match: adding match pattern="mon.*" type=nil
2016-09-01 13:32:48 +0000 [error]: fluent/supervisor.rb:429:rescue in dry_run: dry run failed: undefined method `to_sym' for nil:NilClass
```

I've no familiarity with Ruby so can only surmise that the error is caused by the NIL type. If I add a type though (buffer as the guess), then it complains that the type is not recognised. It may of course have nothing to do with the type, but I'm at the limit of my knowledge on how to track this down further.

### PR DESCRIPTION
**Pull request by tagomoris**
Previously, it raises NeMethodError for nil.
```
2016-09-02 09:45:47 +0900 [error]: unexpected error error="undefined method `to_sym' for nil:NilClass\nDid you mean?  to_s"
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/registry.rb:39:in `lookup'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/plugin.rb:146:in `new_impl'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/plugin.rb:104:in `new_output'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/agent.rb:133:in `add_match'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/agent.rb:69:in `block in configure'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/agent.rb:63:in `each'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/agent.rb:63:in `configure'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/root_agent.rb:86:in `configure'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/engine.rb:119:in `configure'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/engine.rb:93:in `run_configure'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/supervisor.rb:673:in `run_configure'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/supervisor.rb:435:in `block in run_worker'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/supervisor.rb:606:in `main_process'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/supervisor.rb:431:in `run_worker'
  2016-09-02 09:45:47 +0900 [error]: /Users/tagomoris/github/fluentd/lib/fluent/command/fluentd.rb:271:in `<top (required)>'
  2016-09-02 09:45:47 +0900 [error]: bin/fluentd:5:in `require'
  2016-09-02 09:45:47 +0900 [error]: bin/fluentd:5:in `<main>'
```

This fix makes the situation better.
```
2016-09-02 09:48:17 +0900 [error]: config error file="example/match_without_type.conf" error="Missing 'type' parameter on <match> directive"
```

fix #1201.

### CODE REVIEW

File: lib/fluent/agent.rb [hunk 1]
```diff
@@ -63,6 +63,7 @@ def configure(conf)
       conf.elements('filter', 'match').each { |e|
         pattern = e.arg.empty? ? '**' : e.arg
         type = e['@type']
+        raise ConfigError, "Missing 'type' parameter on <#{e.name}> directive" unless type
```
Comment (repeatedly) [inline lib/fluent/agent.rb]: Should use `@type`, not `type`.

Comment (tagomoris) [inline lib/fluent/agent.rb]: Right... I copied it from other error.
