### PR TITLE
Fix monitor agent compatibility

### LINKED ISSUE #1226: monitor_agent does strange output in v0.14
monitor_agent's ouput in v0.14 is weird and different from in v0.12. With folloing configuration:

```
<source>
  @type monitor_agent
</source>

<match nginx>
  @type copy
  <store>
    @type stdout
  </store>
</match>

<match nginx2>
  @type stdout
</match>
```

in v0.12.29

```
$ curl http://localhost:24220/api/plugins
plugin_id:object:3fe8b81d9c10	plugin_category:input	type:monitor_agent	output_plugin:false	retry_count:
plugin_id:object:3fe8b857d768	plugin_category:output	type:copy	output_plugin:true	retry_count:
plugin_id:object:3fe8b857c46c	plugin_category:output	type:stdout	output_plugin:true	retry_count:
plugin_id:object:3fe8b81f4038	plugin_category:output	type:stdout	output_plugin:true	retry_count:
```

in v0.14.6

```
$ curl http://localhost:24220/api/plugins
plugin_id:object:3fa09f9fad74	plugin_category:input	type:monitor_agent	output_plugin:false	retry_count:
plugin_id:object:3fa09f53ae4c	plugin_category:unknown	type:copy	output_plugin:false	retry_count:0
plugin_id:object:3fa09f4ed32c	plugin_category:output	type:stdout	output_plugin:true	buffer_total_queued_size:0	retry_count:0
plugin_id:object:3fa09f4ed32c	plugin_category:output	type:stdout	output_plugin:true	buffer_total_queued_size:0	retry_count:0
plugin_id:object:3fa09fa5e5e0	plugin_category:output	type:stdout	output_plugin:true	buffer_total_queued_size:0	retry_count:0
```

There seems to be 3 issues.

1. `copy` plugin is categorized as `unknown`
2. `stdout` plugin inside `copy` plugin is duplicate
3. `stdout` plugin is not buffered output plugin but displays metrics for buffered plugin such as `buffered_total_queue_size`

### PR DESCRIPTION
**Pull request by tagomoris**
fix #1226.

### CODE REVIEW

**Comment by tagomoris** [comment]
@repeatedly Please review this too.

File: lib/fluent/plugin/output.rb [hunk 1]
```diff
@@ -326,6 +326,7 @@ def start
           @buffering = prefer_buffered_processing
           if !@buffering && @buffer
             @buffer.terminate # it's not started, so terminate will be enough
+            @buffer = nil
```
Comment (repeatedly) [inline lib/fluent/plugin/output.rb]: It seems error prune.
Using configured value is better for detecting output plugin is un-buffered or buffered.

Comment (tagomoris) [inline lib/fluent/plugin/output.rb]: Non-buffered output plugin (without `#write` method) doesn't have values on `@buffer`.
And, output plugin instances which runs this line is determined as non-buffered plugin. So the `@buffer` value is unassigned.
No bad/wrong things there are.

Comment (repeatedly) [inline lib/fluent/plugin/output.rb]: I see. If so, adding comment is better like "This line is needed for detecting buffer or non-buffer, e.g. used by in_monitor_agent".
Only this line, it looks like for GC.

And we should move this `:buffer` reader from `for test` to above `attr_reader` lines.
https://github.com/fluent/fluentd/blob/24e15f3cfcb46029b1dee080bf50b576f573553e/lib/fluent/plugin/output.rb#L145

Comment (tagomoris) [inline lib/fluent/plugin/output.rb]: No. `@buffering` shows this plugin is buffered or non-buffered. Unassigning `@buffer` is just to avoid side-effect in `in_monitor_agent`.

Comment (tagomoris) [inline lib/fluent/plugin/output.rb]: And `@buffer` is still only for tests.

Comment (repeatedly) [inline lib/fluent/plugin/output.rb]: I understand the situation. Adding comment is better with "Avoid side-effect that in_monitor_agent shows non-buffered plugins as buffered."

Comment (tagomoris) [inline lib/fluent/plugin/output.rb]: Done.

**Comment by repeatedly** [comment]
LGTM
