### PR TITLE
Make sure parser returns hash

### LINKED ISSUE #4100: JSON parser plugin can sometimes output records as strings rather than `Hash`
### Describe the bug

The JSON parser plugin can sometimes emit records as a string rather than as a `Hash`. Similar to https://github.com/fluent/fluentd/issues/1279, the expectation of plugins further down the line is that the record it receives is **always** a `Hash`, but this contract is broken in some circumstances by the JSON plugin leading to some very difficult to diagnose bugs.

This happens because a string is considered valid JSON ([SO](https://stackoverflow.com/questions/7487869/is-this-simple-string-considered-valid-json)) and the JSON parser (Oj at least) treats it as such and parses it successfully. But the thing it outputs from it's parsing is not a `Hash` type, it is a string, and at no point in the JSON parser does it throw if the record it is returning isn't a `Hash` object.

### To Reproduce

If you setup a fluentd configmap which a super simple JSON filter setup:
```
    <filter gearset.*>
      @type parser
      <parse>
        @type json
        json_parser oj
      </parse>
      replace_invalid_sequence true
      key_name message
      emit_invalid_record_to_error false
    </filter>
```

When presented with a record which has `{"message": "\"HELLO\""}` it will parse it so that the resulting record is `"HELLO"` (i.e. not a `Hash` type, but just a string. This then causes errors in plugins further down the line (for example in my example this was followed by the Prometheus plugin which threw an error `undefined method `map' for #<String:0x00007fdbb6b32308>\nDid you mean?  tap` which was rather hard to debug).

### Expected behavior

I would of expected the parser plugin to call error out if the thing it was parsing is a string (i.e. the same behaviour you see if the parser failed to parse the JSON).
Potentially I would just expect us to check if `values` is a `Hash` on https://github.com/fluent/fluentd/blob/d5df992d844af38233c4d3788de714d644ddb6c4/lib/fluent/plugin/filter_parser.rb#L74

But that might change behaviour in an unexpected way for people, so it might need to be a configuration value. It is this question what led me to doing an Issue rather than a PR

### Your Environment

```markdown
- Fluentd version: `fluentd 1.14.6`
- Operating system: `PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"`
- Kernel version: `5.10.102.1-microsoft-standard-WSL2`
```

### Your Configuration

```apache
<source>
      @type tail
      read_from_head true
      path /var/log/containers/__.log
      pos_file /fluentd/pos/__.log.pos
      tag gearset.x
      <parse>
        @type cri
      </parse>
    </source>

    <filter gearset.*>
      @type parser
      <parse>
        @type json
        json_parser oj
      </parse>
      replace_invalid_sequence true
      key_name message
      emit_invalid_record_to_error false
    </filter>

    <filter gearset.*>
      @type prometheus
      <metric>
        name na
        type counter
        desc NA
        <labels>
          tag ${tag}
        </labels>
      </metric>
    </filter>
```

Note the plugin which causes the error is the JSON plugin because it is emitting records of string type, but it is the Prometheus plugin which is throwing the error because it is the next thing handling the records (and is not designed to be able to)

### Your Error Log

```shell
dump an error event: error_class=NoMethodError error="undefined method `map' for #<String:0x00007fdbb6b32308>\nDid you mean?  tap" location="/usr/local/bundle/gems/fluent-plugin-prometheus-2.0.3/lib/fluent/plugin/prometheus.rb:90:in `stringify_keys'" tag="gearset.x" time=2023-03-14 12:48:13.381801632 +0000 record="HELLO"
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by daipom**
**Which issue(s) this PR fixes**: 
* Partially Fixes #4100 
* Remake #4106
  * Add fixes for `parser_msgpack` and some refactoring

**What this PR does / why we need it**: 
* Make sure `parser_json` and `parser_msgpack` return Hash.
* Make `parser_json` and `parser_msgpack` accept only `Hash` or `Array` of `Hash`

It is wrong for Parser to return a record that is not Hash.
Subsequent processing may result in errors.

`parser_json` and `parser_msgpack` could return non-Hash objects, so they have been fixed in this PR.
In addition, `in_http` was designed based on this wrong behavior, so it has been fixed as well in this PR.

**However, we have a remaining problem with `filter_parser`.**
`filter_parser` could return Array based on this wrong behavior.
This PR disables it, so it can not return multiple parsed results anymore.
Even though it was wrong to begin with, it's possible that this change in specifications would be unacceptable.
We need to consider this change carefully.
I explain some examples in detail below.

**Docs Changes**:
TODO

**Release Note**: 
TODO

# Example: parser_json

## Case: No subsequent processing (without `convert_values`)

* Before: Array => Single record
* After: Array => Multiple records

Config

```xml
<source>
  @type tcp
  tag test.tcp
  <parse>
    @type json
  </parse>
</source>

<match test.**>
  @type stdout
</match>
```

Operation

```console
$ netcat 0.0.0.0 5170
[{"k":"v"}, {"k2":"v2"}]
```

Result BEFORE this fix

```
2023-03-21 23:30:30.623063804 +0900 test.tcp: [{"k":"v"},{"k2":"v2"}]
```

Result AFTER this fix

```
2023-03-21 23:29:20.147728222 +0900 test.tcp: {"k":"v"}
2023-03-21 23:29:20.147754433 +0900 test.tcp: {"k2":"v2"}
```

## Case: No subsequent processing (with `convert_values`)

* Before: Array => **NoMethodError**
* After: Array => Multiple records

Config

```xml
<source>
  @type tcp
  tag test.tcp
  <parse>
    @type json
    null_empty_string
  </parse>
</source>

<match test.**>
  @type stdout
</match>
```

Operation

```console
$ netcat 0.0.0.0 5170
[{"k":"v"}, {"k2":"v2"}]
```

Result BEFORE this fix

```
2024-04-26 18:48:43 +0900 [error]: #0 unexpected error on reading data host="127.0.0.1" port=33268 error_class=NoMethodError error="undefined method `each_key' for [{\"k\"=>\"v\"}, {\"k2\"=>\"v2\"}]:Array"
```

Result AFTER this fix

```
2024-04-26 18:51:02.763961229 +0900 test.tcp: {"k":"v"}
2024-04-26 18:51:02.763971914 +0900 test.tcp: {"k2":"v2"}
```

## Case: With subsequent filter processing

* Before: Array => **NoMethodError**
* After: Array => Multiple records

Config

```xml
<source>
  @type tcp
  tag test.tcp
  <parse>
    @type json
  </parse>
</source>

<filter test.**>
  @type record_transformer
  enable_ruby true
  <record>
    class ${record.class}
  </record>
</filter>

<match test.**>
  @type stdout
</match>
```

Operation

```console
$ netcat 0.0.0.0 5170
[{"k":"v"}, {"k2":"v2"}]

```

Result BEFORE this fix

```
2023-03-21 23:30:51 +0900 [warn]: #0 dump an error event: error_class=NoMethodError error="undefined method `merge!' for [{\"k\"=>\"v\"}, {\"k2\"=>\"v2\"}]:Array" location="/home/daipom/work/fluentd/fluentd/lib/fluent/plugin/filter_record_transformer.rb:135:in `reform'" tag="test.tcp" time=2023-03-21 23:30:51.040692881 +0900 record=[{"k"=>"v"}, {"k2"=>"v2"}]
```

Result AFTER this fix

```
2023-03-21 23:29:55.783183244 +0900 test.tcp: {"k":"v","class":"Hash"}
2023-03-21 23:29:55.783215076 +0900 test.tcp: {"k2":"v2","class":"Hash"}
```

# Example: filter_parser

## Case: No subsequent processing (without any option)

* Before: Array => Single record
* After: Array => **Imcomleted single record that has only the first value** **!!Remaining Problem!!**

Config

```xml
<source>
  @type sample
  tag test.array
  sample {"message": "[{\"k\":\"v\"}, {\"k2\":\"v2\"}]"}
</source>

<filter test.**>
  @type parser
  key_name message
  <parse>
    @type json
  </parse>
</filter>

<match test.**>
  @type stdout
</match>
```

Result BEFORE this fix

```
2024-04-26 18:53:30.029602646 +0900 test.array: [{"k":"v"},{"k2":"v2"}]
```

Result AFTER this fix

```
2024-04-26 18:55:28.010836436 +0900 test.array: {"k":"v"}
```

## Case: No subsequent processing (with some options such as `reserve_data`)

* Before: Array => **ParserError and return the original record**
  * `parse failed no implicit conversion of Array into Hash`
* After: Array => **Imcomleted record that has only the first value** **!!Remaining Problem!!**

Config

```xml
<source>
  @type sample
  tag test.array
  sample {"message": "[{\"k\":\"v\"}, {\"k2\":\"v2\"}]"}
</source>

<filter test.**>
  @type parser
  key_name message
  reserve_data
  <parse>
    @type json
  </parse>
</filter>

<match test.**>
  @type stdout
</match>
```

Result BEFORE this fix

```
2024-04-26 18:58:25 +0900 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="parse failed no implicit conversion of Array into Hash" location="/home/daipom/work/fluentd/fluentd/lib/fluent/plugin/filter_parser.rb:110:in `rescue in filter_with_time'" tag="test.array" time=2024-04-26 18:58:25.027466823 +0900 record={"message"=>"[{\"k\":\"v\"}, {\"k2\":\"v2\"}]"}
2024-04-26 18:58:25.027466823 +0900 test.array: {"message":"[{\"k\":\"v\"}, {\"k2\":\"v2\"}]"}
```

Result AFTER this fix

```
2024-04-26 18:58:08.091274876 +0900 test.array: {"message":"[{\"k\":\"v\"}, {\"k2\":\"v2\"}]","k":"v"}
```

## Case: With subsequent filter processing

* Before: Array => **dump an error event: error_class=NoMethodError**
* After: Array => **Imcomleted record that has only the first value** **!!Remaining Problem!!**

Config

```xml
<source>
  @type sample
  tag test.array
  sample {"message": "[{\"k\":\"v\"}, {\"k2\":\"v2\"}]"}
</source>

<filter test.**>
  @type parser
  key_name message
  <parse>
    @type json
  </parse>
</filter>

<filter test.**>
  @type record_transformer
  enable_ruby true
  <record>
    class ${record.class}
  </record>
</filter>

<match test.**>
  @type stdout
</match>
```

Result BEFORE this fix

```
2024-04-26 19:06:23 +0900 [warn]: #0 dump an error event: error_class=NoMethodError error="undefined method `merge!' for [{\"k\"=>\"v\"}, {\"k2\"=>\"v2\"}]:Array" location="/home/daipom/work/fluentd/fluentd/lib/fluent/plugin/filter_record_transformer.rb:135:in `reform'" tag="test.array" time=2024-04-26 19:06:23.032939419 +0900 record=[{"k"=>"v"}, {"k2"=>"v2"}]
```

Result AFTER this fix

```
2024-04-26 19:07:25.096004693 +0900 test.array: {"k":"v","class":"Hash"}
```

### CODE REVIEW

File: lib/fluent/plugin/parser_json.rb [hunk 1]
```diff
@@ -70,16 +70,33 @@ def configure_json_parser(name)
       end
 
       def parse(text)
-        record = @load_proc.call(text)
-        time = parse_time(record)
-        if @execute_convert_values
```
Comment (ashie) [inline lib/fluent/plugin/parser_json.rb:75]: Note: No need to check `@execute_convert_values` here because it's also checked in `convert_values`.

**Review by ashie — APPROVED** [review]
LGTM

**Comment by daipom** [comment]
Thanks! I have added `Release Note` to https://github.com/fluent/fluentd/pull/4474#issue-2265457668.
