### PR TITLE
Fix logger initialization

### LINKED ISSUE #4037: Logger: Log format setting is not applied to the first log
### Describe the bug

I noticed this issue when I was checking #4011.

The log of initializing logger is added in Fluentd v1.15.3 at #3939:
Fluentd outputs this log first.

```
2023-02-03 19:24:28 +0900 [info]: fluent/log.rb:330:info: init supervisor logger path=nil rotate_age=nil rotate_size=nil
```

However, the [log format](https://docs.fluentd.org/deployment/logging#log-format) is not applied to this log.

* https://github.com/fluent/fluentd/blob/v1.15.3/lib/fluent/supervisor.rb#L451-L452
* https://github.com/fluent/fluentd/blob/v1.15.3/lib/fluent/supervisor.rb#L586

At the point of `LoggerInitializer::init()`, the format is not applied yet, so the logger must not output logs.

### To Reproduce

Run Fluentd v1.15.3 by the following config and see the first log.

```console
$ bundle exec fluentd -c /path/to/fluent.conf
```

### Expected behavior

[Log format setting](https://docs.fluentd.org/deployment/logging#log-format) is applied to the all logs of Fluentd.

### Your Environment

- Fluentd version: v1.15.3
- Operating system:
  ```console
  $ cat /etc/os-release
  NAME="Ubuntu"
  VERSION="20.04.5 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 20.04.5 LTS"
  VERSION_ID="20.04"
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  VERSION_CODENAME=focal
  UBUNTU_CODENAME=focal
  ```
- Kernel version:
  ```console
  $ uname -r
  5.15.0-58-generic
  ```

### Your Configuration

```apache
<system>
  <log>
    format json
    time_format %Y-%m-%dT%H:%M:%S%z
  </log>
</system>

<source>
  @type sample
  tag test
</source>

<match test.**>
  @type stdout
</match>
```

### Your Error Log

```shell
2023-02-03 19:24:28 +0900 [info]: fluent/log.rb:330:info: init supervisor logger path=nil rotate_age=nil rotate_size=nil
{"time":"2023-02-03T19:24:28+0900","level":"info","message":"parsing config file is succeeded path=\"../work/fluent.conf\""}
{"time":"2023-02-03T19:24:28+0900","level":"info","message":"gem 'fluentd' version '1.15.3'"}
...
```

### Additional context

_No response_

### LINKED ISSUE #4056: Test: Some tests overwrite the global logger for tests
### Describe the bug

Fluentd prepares a global logger with DummyLogDevice for tests.

https://github.com/fluent/fluentd/blob/bf7498d6ff2805bfa517bbd6f7c17103c7d879d4/test/helper.rb#L151-L155

However, some tests overwrite this global logger.

* https://github.com/fluent/fluentd/blob/bf7498d6ff2805bfa517bbd6f7c17103c7d879d4/test/test_logger_initializer.rb#L23
* https://github.com/fluent/fluentd/blob/bf7498d6ff2805bfa517bbd6f7c17103c7d879d4/test/test_supervisor.rb#L862-L876
* https://github.com/fluent/fluentd/blob/bf7498d6ff2805bfa517bbd6f7c17103c7d879d4/test/test_supervisor.rb#L727-L731

Is this as intended?
Is this affecting other tests depending on the test order?

I was trying to fix `test_logger_initializer` in the following PR, and I found this test may affect other tests.

* #4054

I thought I needed to make sure the logger on the global was not changed, but when I looked into it, other tests are also overwriting the logger on the global, so I am not sure what is correct...

-> This can cause unintended behavior depending on the test order, so we should fix this.

### To Reproduce

None

### Expected behavior

None

### Your Environment

```markdown
None
```

### Your Configuration

```apache
None
```

### Your Error Log

```shell
None
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by daipom**
**Which issue(s) this PR fixes**: 
* Fixes #4037
* Fixes #4056

**What this PR does / why we need it**: 
This fix prevents the logger from outputting some initial log messages with some settings not applied, such as `format`. (Please see #4037).

In addition,  the logic of initializing the logger is so difficult and has caused many bugs.
This fix simplifies it.

This fix consists of the following points.

* All logger parameters are now set in the first initialization.
  * Previously, only parameters related to rotation were applied first, but it is preferable to apply all parameters on that point.
* Remove `LoggerInitializer`
  * This class was a source of confusion because its role is difficult to understand.
* Reflect this fix in tests.

**Docs Changes**:
Not needed.

**Release Note**: 
Fix bug that the logger outputs some initial log messages with some settings not applied, such as `format`.

**Additional Context**

Currently, there is a bug in overwriting of `build_system_config()`.
It must prefer the options explicitly specified in the command line.

So `--log-rotate-age` and `--log-rotate-size`  should be merged into `system_config` in `build_system_config()`

https://github.com/fluent/fluentd/blob/ee796efc0d17aaa05496e9a0eb63d61428e170ea/lib/fluent/supervisor.rb#L1050-L1061

However, the log options in `log` directives are not in `Fluent::SystemConfig::SYSTEM_CONFIG_PARAMETERS`, so `--rotate_age` and `--rotate_size` are not merged into `system_config`.

So I have no choice but to give special treatment to the rotation parameters.
(I left comments for now)

### CODE REVIEW

**Comment by ashie** [comment]
Basically it looks good to me. I'm still checking details.

**Comment by daipom** [comment]
Thanks!

File: lib/fluent/log.rb [hunk 1]
```diff
@@ -202,8 +229,12 @@ def time_format=(time_fmt)
...
 
+    def stdout?
+      @out == $stdout
+    end
+
     def reopen!
-      @logger.reopen! if @logger
+      @out.reopen(@path, "a") if @path && @path != "-"
       nil
     end
```
Comment (daipom) [inline lib/fluent/log.rb:239]: Note: The previous logic is meaningless.

This method was not used, and even if this is called, it will do nothing.

https://github.com/treasure-data/serverengine/blob/v2.3.2/lib/serverengine/daemon_logger.rb#L116-L119

https://github.com/treasure-data/serverengine/blob/v2.3.2/lib/serverengine/daemon_logger.rb#L43-L65

`filedev` is always `nil` here.

**Comment by daipom** [comment]
I'll rebase this to apply

* #4096

File: lib/fluent/log.rb [hunk 2]
```diff
@@ -67,8 +67,29 @@ def self.event_tags
       LEVEL_TEXT.map{|t| "#{LOG_EVENT_TAG_PREFIX}.#{t}" }
     end
 
+    # Create a unique path for each process.
+    #
+    # >>> per_process_path(:worker, 1, "C:/tmp/test.log")
```
Comment (abetomo) [inline lib/fluent/log.rb:72]: I thought `per_process_path("C:/tmp/test.log", :worker, 1)` was easier to understand because the order of the arguments is the same.

Comment (daipom) [reply lib/fluent/log.rb:72]: Wow, indeed. Thanks for the advice.
Why wasn't it a match...

Comment (daipom) [reply lib/fluent/log.rb:72]: Looks like we missed it from the start. I'll fix this. Thanks!

**Comment by daipom** [comment]
All tests on Windows succeed!! Yay!!

File: lib/fluent/log.rb (hunk 2 above)
Comment (daipom) [reply lib/fluent/log.rb]: Fixed

https://github.com/fluent/fluentd/compare/879eeecc1f1f4865e554be2f3057f8ad71cfe7ba..a9f511345a9adec2f4f5b78de8e741de3ef7de56

**Review by ashie — APPROVED** [review]
LGTM

**Comment by ashie** [comment]
Thanks!

**Comment by daipom** [comment]
Thanks for your review!
