### PR TITLE
Lifecycle method called correctly once

### LINKED ISSUE #1222: Methods for shutdown sequence called twice
```
2016-09-09 13:05:38 +0000 [info]: shutting down output plugin type=:copy plugin_id="object:2b1675dfb4dc"
2016-09-09 13:05:38 +0000 [info]: shutting down output plugin type=:file plugin_id="turbolog"
2016-09-09 13:05:38 +0000 [info]: shutting down output plugin type=:loggly_buffered plugin_id="object:2b1676325584"
2016-09-09 13:05:38 +0000 [info]: shutting down output plugin type=:file plugin_id="turbolog"
2016-09-09 13:05:38 +0000 [info]: shutting down output plugin type=:loggly_buffered plugin_id="object:2b1676325584"
2016-09-09 13:05:38 +0000 [info]: shutting down filter plugin type=:stdout plugin_id="object:2b1675f79fac"
2016-09-09 13:05:38 +0000 [info]: closing input plugin type=:tail plugin_id="object:2b167625ca58"
2016-09-09 13:05:38 +0000 [info]: closing input plugin type=:tail plugin_id="object:2b1675f2f560"
2016-09-09 13:05:38 +0000 [info]: closing input plugin type=:tail plugin_id="object:2b1675f1c2bc"
2016-09-09 13:05:38 +0000 [info]: closing input plugin type=:forward plugin_id="docker-host"
2016-09-09 13:05:38 +0000 [info]: closing input plugin type=:http plugin_id="turbo"
2016-09-09 13:05:38 +0000 [info]: closing input plugin type=:tail plugin_id="object:2b1675f04914"
2016-09-09 13:05:38 +0000 [info]: closing output plugin type=:loggly_buffered plugin_id="object:2b1676325584"
2016-09-09 13:05:38 +0000 [info]: closing output plugin type=:file plugin_id="turbolog"
2016-09-09 13:05:38 +0000 [info]: closing output plugin type=:file plugin_id="turbolog"
2016-09-09 13:05:38 +0000 [info]: closing output plugin type=:copy plugin_id="object:2b1675dfb4dc"
2016-09-09 13:05:38 +0000 [info]: closing output plugin type=:loggly_buffered plugin_id="object:2b1676325584"
2016-09-09 13:05:38 +0000 [warn]: unexpected error while closing on output plugin plugin=Fluent::FileOutput plugin_id="turbolog" error_class=IOError error="closed stream"
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer/file_chunk.rb:120:in `size'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer/file_chunk.rb:120:in `close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer.rb:125:in `block (2 levels) in close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer.rb:124:in `each_pair'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer.rb:124:in `block in close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer.rb:116:in `close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:449:in `close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin_helper/event_emitter.rb:71:in `close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/root_agent.rb:200:in `block (3 levels) in shutdown'
2016-09-09 13:05:38 +0000 [warn]: unexpected error while closing on output plugin plugin=LogglyOutputBuffred plugin_id="object:2b1676325584" error_class=IOError error="closed stream"
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer/file_chunk.rb:120:in `size'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer/file_chunk.rb:120:in `close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer.rb:125:in `block (2 levels) in close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer.rb:124:in `each_pair'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer.rb:124:in `block in close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/buffer.rb:116:in `close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/output.rb:449:in `close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin_helper/event_emitter.rb:71:in `close'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/root_agent.rb:200:in `block (3 levels) in shutdown'
2016-09-09 13:05:38 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `emit_error_event' for nil:NilClass" tag="fluent.info"
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/filter_stdout.rb:46:in `rescue in block in filter_stream'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/filter_stdout.rb:42:in `block in filter_stream'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event.rb:100:in `each'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/filter_stdout.rb:41:in `filter_stream'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:171:in `block in filter_stream'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:171:in `each'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:171:in `reduce'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:171:in `filter_stream'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:152:in `emit_events'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:90:in `emit_stream'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/event_router.rb:81:in `emit'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/engine.rb:165:in `block in log_event_loop'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/engine.rb:163:in `each'
  2016-09-09 13:05:38 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/engine.rb:163:in `log_event_loop'
2016-09-09 13:05:38 +0000 [error]: failed to emit fluentd's log event tag="fluent.info" event={"type"=>:copy, "plugin_id"=>"object:2b1675dfb4dc", "message"=>"shutting down output plugin type=:copy plugin_id=\"object:2b1675dfb4dc\""} error_class=NoMethodError error="undefined method `emit_error_event' for nil:NilClass"
2016-09-09 13:05:38 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `emit_error_event' for nil:NilClass" tag="fluent.info"
  2016-09-09 13:05:38 +0000 [warn]: suppressed same stacktrace
```

* Fluentd 0.14.6
* Output plugin with buffering

### PR DESCRIPTION
**Pull request by tagomoris**
This change is to fix both of #1161 and #1222.

To fix #1222, RootAgent (and Agent) should not retrieve `outputs` of output plugins dynamically in `#lifecycle`. Removing it solves the problem to call shutdown methods twice.

But this fix re-opens #1161 problem.
If all plugins are flat/static plugins or MultiOutput plugins which initialize all stores by static configuration, all plugin instances are registered in `agent.outputs`.
But once MultiOutput plugin is initialized dynamically by any plugins (e.g., fluent-plugin-forest), its sub-store/sub-plugin instances are not registered in `agent.outputs`. Lifecycle methods of these plugins are never called.

This change will add a feature to call lifecycle methods in MultiOutput. It's a kind of dirty workaround, but works well.

### CODE REVIEW

**Comment by tagomoris** [comment]
@repeatedly Could you review this change?

**Comment by repeatedly** [comment]
It seems good. Removing `recursive_output_traverse.call(store)` in `lifecycle` also resolves same inssue with copy_ex like v0.12 MultiOutput based plugin.

File: lib/fluent/agent.rb [hunk 1]
```diff
@@ -137,7 +131,12 @@ def add_match(type, pattern, conf)
       @outputs << output
       if output.respond_to?(:outputs) && (output.respond_to?(:multi_output?) && output.multi_output? || output.is_a?(Fluent::MultiOutput))
```
Comment (repeatedly) [inline lib/fluent/agent.rb]: Another topic.
I noticed adding `Fluent::MultiOutput`'s `outputs` seems wrong.
v0.12 `MultiOutput` calls plugin's `start`/`shutdown` directly, so
it causes double lifecycle sequence calls.

Comment (tagomoris) [inline lib/fluent/agent.rb]: Hmm, looks right.

**Comment by tagomoris** [comment]
@repeatedly updated this change.

**Comment by tagomoris** [comment]
@repeatedly ping.

**Comment by repeatedly** [comment]
LGTM
