### PR TITLE
out_file/out_secondary_file: Support ${chunk_id} placeholder. fix #1705

### LINKED ISSUE #1705: No Way to tie Failed Buffer Chunks to Chunk ID
- V14
- CentOS
- Forwarder web servers, to aggregators

FluentD log files refer to chunk_id when it is emitting errors and warning. Sometimes of these lead to failed chunks. Those failed chunks can be put in a secondary location. However, the ${chunk_id} is not available in the failed log and the meta file is not in the failed folder so this chunk_id can't be used to figure out which specific failed buffer file an error relates to. 

Remedy: file & secondary_file should support something like ${chunk_id} placeholder so that the chunk_id can be retained.

### PR DESCRIPTION
**Pull request by repeatedly**
`${chunk_id}` placeholder is useful for out_file like plugins.
So I added `CHUNK_ID_PLACEHOLDER_PATTERN` in Output to share.
For example, out_webhdfs uses own `${chunk_id}` value but it should use this predefined constant.

### CODE REVIEW

File: lib/fluent/plugin/out_file.rb [hunk 1]
```diff
@@ -178,7 +178,7 @@ def format(tag, time, record)
     end
 
     def write(chunk)
-      path = extract_placeholders(@path_template, chunk.metadata)
+      path = extract_placeholders(@path_template.gsub(CHUNK_ID_PLACEHOLDER_PATTERN, dump_unique_id_hex(chunk.unique_id)), chunk.metadata)
```
Comment (mururu) [inline lib/fluent/plugin/out_file.rb]: It seems better that the replacements of `CHUNK_ID_PLACEHOLDER_PATTERN` should be done by `extract_placeholders` instead of each plugins. For now, only these two plugins use this method, but it is useful if all plugins can use this feature automatically in the future.

Comment (repeatedly) [reply lib/fluent/plugin/out_file.rb]: Yeah, it is one idea.
For it, we need to change `extract_placeholders` API.

1. 2nd argument changed to chunk, not `chunk.metadata`

For compatibility, we need to check 2nd argument type.

```
metadata = chunk.metadata if metadata.is_a?(Chunk)
```

2. Add 3rd argument for chunk

`def extract_placeholders(str, metadata, chunk = nil)`

`metadata` is from `chunk` so this API is a little strange.

3. Add 3rd argument for additional params

This avoids further API changes.

```
def extract_placeholders(str, metadata, extras = nil)
  if extras && extras.has_key?(:chunk)
  end
end
```

I think 1 is better because this doesn't break exsiting API and doesn't add more argument.
We can change Plugin API before stable announcement.

Comment (mururu) [reply lib/fluent/plugin/out_file.rb]: 👍 > 1

**Comment by repeatedly** [comment]
@okkez @cosmo0920 How about above change? Do you have other opinion?

File: lib/fluent/plugin/out_file.rb (hunk 1 above)
Comment (cosmo0920) [reply lib/fluent/plugin/out_file.rb]: I agree to change `extract_placeholders` API.
:+1: > 1 and 3. The both looks good to me.

Comment (okkez) [reply lib/fluent/plugin/out_file.rb]: :+1:  > 1

**Comment by repeatedly** [comment]
Change `extract_placeholders` API. PTAL!
