### PR TITLE
formatter_csv: fix memory leak

### LINKED ISSUE #3627: in_exec with out_exec in one config create file descriptors leak
### Describe the bug

Hello, I think I have found the core issue of my problems with fluentd configuration, could someone have look on this please?
I have set everything according to https://docs.fluentd.org/installation/before-install.
Using configuration and two scripts below I can notice that if I do these for a while:
```
cd /proc/<fluentd PID>/ 
find fd | wc -l
```
Then I can see that number of file descriptors is rising infinitely eventually resulting in memory problems and "too many open files" error because of reaching fd limit (ulimit -n). This only occures if both in_exec and out_exec are used, since if I do following swaps, the number of file descriptors stabilizes. I can do either of these and the problems will disappear.

File descriptors count is stabilized if I swap match section for this:
```
<match hardware.memory>
  @type file
  append true
  path {{ home }}/fluentd/test_bug2.log
  add_path_suffix false
  <buffer []>
    @type memory
    flush_mode immediate
  </buffer>
  <format>
    @type json
  </format>
</match>
```

or swap source and filter section for this:
```
<source>
  @type sample
  sample {"mem_available":"1.5","swap_total":"1.5","swap_free":"1.2","time_local":"2022-02-09T10:00:00+0100"}
  tag hardware.memory
</source>
```

### To Reproduce

Install fluentd:
`gem install fluentd --version 1.14.5 --no-doc`
Create folder "fluentd" in home folder
Exchange {{ home }} or {{ user }} for your real values in every file below.
Put fluentd.conf (with configuration below), get_memory_metrics.sh, psql_memory.sh into {{ home }}/fluentd/
do chmod +x on get_memory_metrics.sh, psql_memory.sh
run {{ home }}/bin/fluentd _1.14.5_ -c {{ home }}/fluentd/fluentd.conf -vv

Now start checking the file descriptors in `/proc/<fluentd PID>/` with:
`find fd | wc -l`
Keep cheking it for some time, youll see the count of file descriptors never stops rising.

Hopefully I did not miss anything.

### Expected behavior

Number of file descriptors is not rising infinitely and not causing memory leaks.

### Your Environment

```markdown
- Fluentd version: 1.14.5 (installed as gem)
- TD Agent version: -
- Operating system: Rocky Linux 8
- Kernel version: 4.18.0-348.12.2.el8_5.x86_64
- Ruby version: 2.5.9
```

### Your Configuration

```apache
<system>
  process_name fluentd_monitor
</system>

<source>
  @type exec
  tag hardware.memory
  run_interval 10s
  command {{ home }}/fluentd/get_memory_metrics.sh
  <parse>
    @type json
    types mem_available:float,swap_total:float,swap_free:float
  </parse>
</source>

<filter hardware.memory>
  @type record_transformer
  enable_ruby
  <record>
    time_local ${time.strftime('%Y-%m-%dT%H:%M:%S%z')}
  </record>
</filter>

<match hardware.memory>
  @type exec
  command {{ home }}/fluentd/psql_memory.sh first_argument second_argument
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields time_local,mem_available,swap_total,swap_free
  </format>
  <buffer time>
    @type file
    path {{ home }}/fluentd/hardware.memory.buff
    timekey 50s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
  <secondary>
    @type secondary_file
    directory {{ home }}/fluentd/secondary/
    basename dump.${chunk_id}
  </secondary>
</match>
```

### Your Error Log

```shell
No errors in fluentd.log using --v
```

### Additional context

**get_memory_metrics.sh** 
```
#!/bin/bash
mem_info=$(awk '{ \
    if (/MemAvailable:/) {mem_available=$2}; \
    if (/SwapTotal:/) {swap_total=$2}; \
    if (/SwapFree:/) {swap_free=$2}; \
    if (mem_available && swap_total && swap_free) \
      {printf "%.3f %.3f %.3f", mem_available/1024/1024, swap_total/1024/1024, swap_free/1024/1024;exit} \
  }' /proc/meminfo)
read -r mem_available swap_total swap_free<<<"${mem_info}"

printf '{"mem_available":"%s","swap_total":"%s","swap_free":"%s"}' \
"$mem_available" \
"$swap_total" \
"$swap_free"
```

**psql_memory.sh** 
```
#!/bin/sh
echo $1 $2 $3
```

### PR DESCRIPTION
**Pull request by Watson1978**
**Which issue(s) this PR fixes**: 
Fixes #3627

**What this PR does / why we need it**: 
Seems `in_exec` plugin creats Thread object each interval and  it invoke formatter_csv on the thread.

If it use a Thread object as hash key when caching with formatter_csv, that thread will be permanently referenceable and will not be collected by the GC.

Here is memory usage of Ruby's process.
chart

### Reproduce
See #3627
```
<system>
  process_name fluentd_monitor
</system>

<source>
  @type exec
  tag hardware.memory
  run_interval 0.1
  command /home/watson/prj/sandbox/fluentd/get_memory_metrics.sh
  <parse>
    @type json
    types mem_available:float,swap_total:float,swap_free:float
  </parse>
</source>

<match **>
  @type exec
  command /home/watson/prj/sandbox/fluentd/psql_memory.sh
  <format>
    @type csv
    force_quotes false
    delimiter |
    fields time_local,mem_available,swap_total,swap_free
  </format>
  <buffer time>
    @type file
    path /home/watson/prj/sandbox/fluentd/log
    timekey 50s
    timekey_wait 0s
    flush_mode lazy
    total_limit_size 200MB
    retry_type periodic  # exponential backoff is broken https://github.com/fluent/fluentd/issues/3609
    retry_max_times 0  # need to go to secondary as soon as possible https://github.com/fluent/fluentd/issues/3610
  </buffer>
</match>
```

**Docs Changes**:

**Release Note**: 
formatter_csv: fix memory leak

### CODE REVIEW

**Review by daipom — COMMENTED** [review]
Thanks! Good catch!

It seems that in #2529, input plugins were assumed to spawn only a fixed number of threads for emitting.
However, `in_exec` for example, makes threads for emitting without limit.
The cache would then become infinitely large.
We need to fix this cache.

**Comment by Watson1978** [comment]
@daipom Thanks. I fixed the key name at last commit.

File: lib/fluent/plugin/formatter_csv.rb [hunk 1]
```diff
@@ -52,11 +57,11 @@ def configure(conf)
         @generate_opts = {col_sep: @delimiter, force_quotes: @force_quotes, headers: @fields,
                           row_sep: @add_newline ? :auto : "".force_encoding(Encoding::ASCII_8BIT)}
         # Cache CSV object per thread to avoid internal state sharing
-        @cache = {}
+        Thread.current[thread_key] = nil
```
Comment (daipom) [inline lib/fluent/plugin/formatter_csv.rb:60]: Just a note.

>         # Cache CSV object per thread to avoid internal state sharing
>        Thread.current[thread_key] = nil

Now, this code would be unnecessary since the key becomes unique for the instance.
However, it may be the correct specification to clear the cache when `configure` is performed.
(I don't know if there is a case for performing `configure` multiple times.)

File: lib/fluent/plugin/formatter_csv.rb [hunk 2]
```diff
@@ -35,6 +36,10 @@ class CsvFormatter < Formatter
       config_param :fields, :array, value_type: :string
       config_param :add_newline, :bool, default: true
 
+      def thread_key
+        "#{plugin_id}_csv"
```
Comment (daipom) [inline lib/fluent/plugin/formatter_csv.rb:40]:
```suggestion
        "#{owner.plugin_id}_csv_formatter_#{usage}_csv"
```

Formatter plugins (owned plugins) are unique to `owner.plugin_id` and `usage`.

**Review by daipom — CHANGES_REQUESTED** [review]
Sorry, I forgot that this is a `owned` plugin.
It would not be expected to have an owned plugin with `PluginId`.

So, could you please fix the following points?

(Owned plugins are unique to the owner's id and `usage`.)

**Comment by Watson1978** [comment]
When it invoke `CsvFormatter` via `Fluent::Compat::TextFormatter`, looks like it does not set `owner`...

**Comment by daipom** [comment]
> When it invoke `CsvFormatter` via `Fluent::Compat::TextFormatter`, looks like it does not set `owner`...

Sorry, I missed this point.
I have pushed another idea to fix this issue.

* 80c02fbb385e51afe925b5083cba92fc8c27ab55

@Watson1978 Could you please review this commit?
If there seem to be some problems, we can revert it.

The aim of this commit is to ensure that the compat layer does not affect this cache feature.
(Because I'm not sure how to make the key unique on the compat layer context.)

File: lib/fluent/compat/formatter.rb [hunk 3]
```diff
@@ -101,6 +101,21 @@ class LabeledTSVFormatter < Fluent::Plugin::LabeledTSVFormatter
...
+        # (We can try, but it would be low priority.)
+        def csv_for_thread
+          CSV.new("".force_encoding(Encoding::ASCII_8BIT), **@generate_opts)
+        end
+
+        # It is hard to consider the thread key correctly for the compat layer.
+        def csv_thread_key
+          raise NotImplementedError, "Compat CsvFormatter does not support CSV cache. Do not use this method."
+        end
+
```
Comment (daipom) [inline lib/fluent/compat/formatter.rb:115]:
```suggestion
```

Looks like overriding `csv_cacheable?` is enough.

File: lib/fluent/plugin/formatter_csv.rb [hunk 4]
```diff
@@ -35,6 +35,22 @@ class CsvFormatter < Formatter
       config_param :fields, :array, value_type: :string
       config_param :add_newline, :bool, default: true
 
+      def csv_cacheable?
+        owner ? true : false
```
Comment (daipom) [inline lib/fluent/plugin/formatter_csv.rb:39]:
```suggestion
        not owner.nil?
```

Simpler?

**Review by daipom — COMMENTED** [review]
Thanks for fixing the CI failures my commit caused!

It seems possible that there is no owner. (FluentBinlogReader)
It would be a good solution to disable the cache feature in such a case.

I commented on some minor points.
Please check them.

File: lib/fluent/compat/formatter.rb (hunk 3 above)
Comment (Watson1978) [reply lib/fluent/compat/formatter.rb:115]: Indeed. Thanks.

File: lib/fluent/plugin/formatter_csv.rb (hunk 4 above)
Comment (Watson1978) [reply lib/fluent/plugin/formatter_csv.rb:39]: Hmm, I think using ternary operator is readable for me...

Comment (kenhys) [reply lib/fluent/plugin/formatter_csv.rb:39]: one more suggestion: `!!owner`

Comment (Watson1978) [reply lib/fluent/plugin/formatter_csv.rb]: Thanks. Replaced with `!!owner`
https://github.com/fluent/fluentd/pull/4864/commits/eae43cae2f08bb94d4601599129ee416bb7038e3

**Review by daipom — APPROVED** [review]
LGTM! Thanks for your contribution!
