### PR TITLE
Windows: Fix an issue where stopping the service immediately after startup could leave the processes

### LINKED ISSUE #3937: Windows Service: Stopping service sometimes can not be completed forever
### Describe the bug

On Windows, we can run fluentd as a Windows Service.

(Windows PowerShell with Administrative privilege)

```console
# Register
> fluentd.bat --reg-winsvc i
> fluentd.bat --reg-winsvc-fluentdopt '-c C:/test/td-agent.conf -o C:/test/td-agent.log'

# Start the service
> Start-Service fluentdwinsvc

# Stop the service
> Stop-Service fluentdwinsvc

# Unregister
> fluentd.bat --reg-winsvc u
```

With certain conditions, `Stop-Service` can not be completed forever.
This happens when multiple supervisor processes are running simultaneously for some reason (perhaps accidentally).

Fluentd uses [Event Objects](https://learn.microsoft.com/en-us/windows/win32/sync/event-objects) for signals on Windows.

* Windows Service process: https://github.com/fluent/fluentd/blob/v1.15.2/lib/fluent/winsvc.rb#L65-L70
* Supervisor process: https://github.com/fluent/fluentd/blob/v1.15.2/lib/fluent/supervisor.rb#L242

This event's type is `Auto-reset event`, so the event is automatically unsignalled when one process receives it.

* `Win32::Event.new`: https://github.com/chef/win32-event/blob/main/lib/win32/event.rb#L63

If another supervisor unintentionally receives the event, the process that should be stopped fails to receive it and continues to run.

This makes the service wait for the stopping process forever.

* https://github.com/fluent/fluentd/blob/v1.15.2/lib/fluent/winsvc.rb#L68

If we kill all fluentd processes (the service process, supervisor, and workers), we can stop the service forcibly.

### To Reproduce

1. Register fluentd as a Windows Service.

```console
> fluentd.bat --reg-winsvc i
> fluentd.bat --reg-winsvc-fluentdopt '-c C:/test/td-agent.conf -o C:/test/td-agent.log'
```

2. We can see 3 ruby processes with a single worker setting.
    * Service process, supervisor,  and worker

```console
> Start-Service fluentdwinsvc
> ps -ProcessName ruby
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
226      22    51128      54896       2.09   1792   0 ruby
128      12    15796      16384       0.25   2812   0 ruby
183      17    38084      43380       1.53   3232   0 ruby
```

4. We can stop the service while leaving the supervisor and worker alive as following.

```console
# First, make sure the service is stopped.
> Stop-Service fluentdwinsvc

# Then, start the service and immediately stop it.
> Start-Service fluentdwinsvc
> Stop-Service fluentdwinsvc

# We can see 2 ruby processes still alive. (supervisor and worker process)
> ps -ProcessName ruby
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
  ...                     ...                   ...        ruby
  ...                     ...                   ...        ruby
```

5. Start the service again, and now we can see 5 processes.
    * This is the situation where multiple supervisor processes are running simultaneously.

```console
> Start-Service fluentdwinsvc
> ps -ProcessName ruby
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
  ...                     ...                   ...        ruby
  ...                     ...                   ...        ruby
  ...                     ...                   ...        ruby
  ...                     ...                   ...        ruby
  ...                     ...                   ...        ruby
```

6. Then we can reproduce this issue by stopping the service again.

Sorry for the Japanese language environment.

```console
> Stop-Service fluentdwinsvc
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
(repeats forever)
```

The messages may be as follows in English

```console
> Stop-Service
WARNING: Waiting for service 'Fluentd Windows Service (fluentdwinsvc)' to stop...
WARNING: Waiting for service 'Fluentd Windows Service (fluentdwinsvc)' to stop...
WARNING: Waiting for service 'Fluentd Windows Service (fluentdwinsvc)' to stop...
(repeats forever)
```

### Expected behavior

The supervisor process of the service stops for sure.

* the pid: https://github.com/fluent/fluentd/blob/v1.15.2/lib/fluent/winsvc.rb#L59

Or, if fluentd doesn't expect multiple supervisors to run simultaneously, all supervisor processes should stop when stopping the service.

### Your Environment

```markdown
- Fluentd version: 1.15.2
- Operating system: Windows 10
```

### Your Configuration

The config has nothing to do with this issue.

```apache
<source>
  @type dummy
  tag test.log
  rate 1
  dummy {"message": "This is the test message"}
</source>

<match test.**>
  @type stdout
</match>
```

### Your Error Log

Sorry for the Japanese language environment

```console
> Stop-Service
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
(repeats forever)
```

The messages may be as follows in English

```console
> Stop-Service
WARNING: Waiting for service 'Fluentd Windows Service (fluentdwinsvc)' to stop...
WARNING: Waiting for service 'Fluentd Windows Service (fluentdwinsvc)' to stop...
WARNING: Waiting for service 'Fluentd Windows Service (fluentdwinsvc)' to stop...
(repeats forever)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by daipom**
**Which issue(s) this PR fixes**: 
* Fixes #3937

**What this PR does / why we need it**: 
Add retry for stop event for Windows Service to fix #3937.

If `Event.open()` ([OpenEvent](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-openeventw)) is called before the `Event.new()` ([CreateEvent](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventw)), `Event.open()` raises `Errno::ENOENT`.
This causes the service to be stopped while the supervisor and worker process remains.
It causes #3937.
This PR fixes it by adding retry.

https://github.com/fluent/fluentd/blob/30c3ce00ff165b1b5d9f53fc0a027074bbcab0da/lib/fluent/winsvc.rb#L90

https://github.com/fluent/fluentd/blob/30c3ce00ff165b1b5d9f53fc0a027074bbcab0da/lib/fluent/supervisor.rb#L299

**Docs Changes**:
Not needed. 

**Release Note**: 
It would be good to have both of the following.

* Windows: Fixed an issue where stopping the service immediately after startup could leave the processes.
* Windows: Fixed an issue where stopping service sometimes can not be completed forever.

### CODE REVIEW

**Comment by daipom** [comment]
# Test

* fluent-package v5.0.2
* Windows 10 Home

## Before

The supervisor and worker processes remain if stopping the service immediately after startup.

Powershell

```console
$ Start-Service fluentdwinsvc; Stop-Service fluentdwinsvc
$ (ps -Name ruby).length
2
```

## After

The supervisor and worker processes stop correctly if stopping the service immediately after startup.

Powershell

```console
$ Start-Service fluentdwinsvc; Stop-Service fluentdwinsvc
$ (ps -Name ruby).length
0
```

**Comment by daipom** [comment]
# Test: If max_retries(`30`) is exceeded, give up stopping the supervisor and stop the service.

Edit the code so that it takes 30 seconds to create the Event.

```diff
--- a/lib/fluent/supervisor.rb
+++ b/lib/fluent/supervisor.rb
@@ -59,6 +59,7 @@ module Fluent
       end

       if Fluent.windows?
+        sleep 30
         install_windows_event_handler
       else
         install_supervisor_signal_handlers
```

Powershell

```powershell
$ Start-Service fluentdwinsvc; Stop-Service fluentdwinsvc
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
警告: サービス 'Fluentd Windows Service (fluentdwinsvc)' の停止を待っています...
$ (ps -Name ruby).length
2
$ Get-Service fluentdwinsvc

Status   Name               DisplayName
------   ----               -----------
Stopped  fluentdwinsvc      Fluentd Windows Service
```

File: lib/fluent/winsvc.rb [hunk 1]
```diff
@@ -91,6 +94,24 @@ def set_event(event_name)
...
+      retries = 0
+      max_retries = 10
+      delay_sec = 3
+
+      begin
+        set_event(event_name)
+      rescue Errno::ENOENT
+        # This error occurs when the supervisor process has not yet created the event.
+        # If STOP is immediately executed, this state will occur.
+        # Retry `set_event' to wait for the initilization of the supervisor.
```
Comment (kenhys) [inline lib/fluent/winsvc.rb:108]:
```suggestion
        # Retry `set_event' to wait for the initialization of the supervisor.
```

File: lib/fluent/winsvc.rb [hunk 2]
```diff
@@ -91,6 +94,24 @@ def set_event(event_name)
       ev.set
       ev.close
     end
+
+    def repeat_set_event_several_times_until_success(event_name)
+      retries = 0
+      max_retries = 10
```
Comment (ashie) [inline lib/fluent/winsvc.rb:100]: nitpick: The name might be misleading because it seems including the first try.

**Review by ashie — DISMISSED** [review]
LGTM

File: lib/fluent/winsvc.rb [hunk 3]
```diff
@@ -63,10 +63,13 @@ def service_main
...
     def service_stop
-      set_event(@service_name)
-      if @pid > 0
-        Process.waitpid(@pid)
+      if @pid <= 0
+        set_event(@service_name)
+        return
       end
+
+      repeat_set_event_several_times_until_success(@service_name)
```
Comment (kenhys) [inline lib/fluent/winsvc.rb:71]: It might exist better alternative name.

* wait_until_ready_for_supervisor_event_processing
* wait_until_ready_for_supervisor_event_handling

Any other good idea?

**Review by kenhys — CHANGES_REQUESTED** [review]
Fix itself seems LGTM.
There is a nitpick about naming.

File: lib/fluent/winsvc.rb (hunk 1 above)
Comment (daipom) [reply lib/fluent/winsvc.rb]: Thanks!

File: lib/fluent/winsvc.rb (hunk 2 above)
Comment (ashie) [reply lib/fluent/winsvc.rb:100]: Sorry, I misunderstood. It doesn't include first try.

File: lib/fluent/winsvc.rb (hunk 3 above)
Comment (daipom) [reply lib/fluent/winsvc.rb:71]: Thanks! but it seems to me that the current name is a straightforward expression of what this method does.
What aspects do you feel are problematic?
Would it be easier to understand if the name reflects the purpose of the method?

>     * wait_until_ready_for_supervisor_event_processing
>     * wait_until_ready_for_supervisor_event_handling

For these names, I'm concerned about the following points.

* The main action of this method is `set_event`, not `wait`. (They don't tell us about `set_event`.)
* It is possible to give up waiting.

Comment (daipom) [reply lib/fluent/winsvc.rb]: How about this?: ddb51b814da90c6fe686a0522502ecf5b6167c07

**Review by kenhys — APPROVED** [review]
LGTM.

File: lib/fluent/winsvc.rb (hunk 3 above)
Comment (kenhys) [reply lib/fluent/winsvc.rb]: LGTM.

**Comment by daipom** [comment]
Thanks for your review!
