### PR TITLE
in_tail: Shutdown immediately & safely even if reading huge files

### LINKED ISSUE #3323: Tail input plugin doesn't respect SIGTERM  signal
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

**Describe the bug**
We use tail input plugin to read logs. And Fluentd is deployed as daemonset in Kubernetes. During deployment, Kubernetes will first send a SIGTERM signal to Fluentd container to ask it to gracefully shut down. But tail input plugin keeps reading data until the container eventually killed. 

**To Reproduce**
Run Fluentd in Kubernetes and trigger a deployment. 

**Expected behavior**
When receive SIGTERM, tail should stop reading, keep record of current position and flush out memory buffers. 

**Your Environment**

- Fluentd or td-agent version: `td-agent 4.1.0 fluentd 1.12.1 (e3effa337593618cbd7f0f4ef071766df1ec69a0)`
- Operating system: `Ubuntu 18.04.5 LTS (Bionic Beaver)`
- Kernel version: `5.4.0-1039-azure`

If you hit the problem with older fluentd version, try latest version first.

**Your Configuration**

```
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /var/log/fluentd-containers.log.pos
  time_key @timestamp
  tag kubernetes.*
  format json
  read_from_head true
</source>
```

**Your Error Log**

```
N/A
```

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by ashie**
**Which issue(s) this PR fixes**: 
Fixes #3323 #3345 #3333 (maybe)

**What this PR does / why we need it**: 
in_tail takes very long time to shutdown when it's reading huge files.
This patch ensure to shutdown ASAP just after receiving a shutdown
command.
    
* Constructed tail watchers should be registered ASAP to be recognized
  by the shutdown process.
* Break `TailWatcher#on_notify` ASAP
  Wait 5 secdonds before breaking it to ensure reading remaining lines.
    
It takes effect only when `skip_refresh_on_startup` is enabled, because
reading files is occurred on main thread without it. It should be
enabled by default in the future.

**Docs Changes**:
none

**Release Note**: 
Same as title

### CODE REVIEW

File: lib/fluent/plugin/in_tail.rb [hunk 1]
```diff
@@ -965,16 +976,18 @@ def handle_notify
...
-                    end
                     if limit_bytes_per_second_reached?
                       # Just get out from tailing loop.
                       read_more = false
                       break
                     end
+                    if @lines.size >= @read_lines_limit
+                      # not to use too much memory in case the file is very large
+                      @ready_to_shutdown_mutex.synchronize {
+                        read_more = !@ready_to_shutdown
```
Comment (ashie) [inline lib/fluent/plugin/in_tail.rb:987]: I think it should wait a few seconds instead of aborting immediately.

File: lib/fluent/plugin/in_tail.rb [hunk 2]
```diff
@@ -718,6 +720,7 @@ def register_watcher(watcher)
       end
 
       def detach
+        @io_handler.ready_to_shutdown if @io_handler
```
Comment (ashie) [inline lib/fluent/plugin/in_tail.rb:723]: `detach` is called not only when shutdown but also on refreshing watchers.
But I think we don't need consider the later case because it will occur only when idling case (not occur while running `on_notify`).

File: lib/fluent/plugin/in_tail.rb [hunk 3]
```diff
@@ -490,9 +490,11 @@ def update_watcher(target_info, pe)
 
         if new_position_entry.read_inode == 0
           @tails[new_target_info] = setup_watcher(new_target_info, new_position_entry)
+          @tails[new_target_info].on_notify
```
Comment (ashie) [inline lib/fluent/plugin/in_tail.rb:493]: Constructed watchers should be registered ASAP, before running `on_notify`.
Otherwise shutting down process can't recognize the watcher so that it won't be killed.
This is the why the error I mentioned at https://github.com/fluent/fluentd/issues/3323#issuecomment-830634918 is occurred.

File: lib/fluent/plugin/in_tail.rb (hunk 1 above)
Comment (ashie) [reply lib/fluent/plugin/in_tail.rb]: Done.

**Comment by ashie** [comment]
This patch might fixes also #3333, but a bit more change may be needed to address it.
I'll confirm it before merging it.

**Comment by ashie** [comment]
> It takes effect only when `skip_refresh_on_startup` is enabled, because reading files is occurred on main thread without it.

Because it's executed at:

https://github.com/fluent/fluentd/blob/b6ba1c27db9a1f1b736b20c1c5018ed6cd88a01e/lib/fluent/plugin/in_tail.rb#L246

it blocks:

https://github.com/fluent/fluentd/blob/b6ba1c27db9a1f1b736b20c1c5018ed6cd88a01e/lib/fluent/engine.rb#L144-L148

so that trailing main loop isn't executed yet on this case.

I'm now considering how to stop on this case.
Even if in this case, `TERM` signal handler is worked and `@engine_stopped` of `Fluent::Engine` is set.
So we can stop `handle_notify` by checking it.
But I think it's not smart design, make `skip_refresh_on_startup` default is the appropriate way I think.
Probably it's harmless but not certain.

**Comment by fujimotos** [comment]
@ashie I'm testing this PR on my machine. WFM.

**Review by fujimotos — APPROVED** [review]

**Comment by fujimotos** [comment]
I can confirm this PR fixes #3323: Sending `killall -TERM fluentd` 
stops `in_tail` after 5 seconds (when this PR is applied):

```console
$ bundle exec fluentd -c fluentd.conf
...
2021-05-24 23:44:17 +0900 [info]: #0 shutting down fluentd worker worker=0
2021-05-24 23:44:17 +0900 [info]: #0 shutting down input plugin type=:tail plugin_id="object:2adaf83ea9ec"                                                              
2021-05-24 23:44:22 +0900 [info]: #0 shutting down output plugin type=:null plugin_id="object:2adaf837b128"
```

The configuration file I used for the testing was:

```xml
<source>
  @type tail
  tag debug.log
  path data.txt
  read_from_head true
  skip_refresh_on_startup true
  refresh_interval 1s
  <parse>
    @type json
  </parse>
</source>

<match debug.**>
  @type null
</match>
```

and the data file was:

```console
$ ls -hl data.txt
-rw-r--r-- 1 jailbird jailbird 181M May 24 23:29 data.txt
$ head -n3 data.txt
{"hello": 0}
{"hello": 1}
{"hello": 2}
```

So I believe this PR is mergeable.

**Comment by fujimotos** [comment]
> It takes effect only when skip_refresh_on_startup is enabled, because reading files is occurred on main thread without it.

I expect that this won't be so much a big issue, because:

 * The "main thread" blocking occurs just once: during the initialization phase of `in_tail`.
 * After we pass that phase, `SIGTERM`  works, regardless of `skip_refresh_on_startup` enabled or not.
 * For this reason, this issue occurs mostly when users try to shutdown Fluentd immediately after boot.
   * ... which I believe a rare thing to do.

> I'm now considering how to stop on this case.
> ...
> Probably it's harmless but not certain...

I think the most expedient fix is _"Don't read the file in main thread."._

Probably we can just create a new thread and kick `refresh_watcher` there:

```ruby
def start:
    ...
    Thread.new do 
        refresh_watchers unless @skip_refresh_on_startup
    end     
end
```

... or maybe we should add a new option `immediate` to `timer_execute()`,
to let it start executing the callback without delays.

But either way, I think we can fix that in another PR.

**Comment by ashie** [comment]
Thanks for your review!

**Comment by ashie** [comment]
> ... or maybe we should add a new option `immediate` to `timer_execute()`,
> to let it start executing the callback without delays.

refs: #1502 #1504
