### PR TITLE
Provide CRLF newline style choice on formatter plugins. Fix #3151

### LINKED ISSUE #3151: File output on Windows missing CRLF
**Describe the bug**
File outputs only have Unix line endings (LF), and some tools are having trouble reading files without CRLF on Windows.

**To Reproduce**
1. Read any input
2. Write to a file
3. File will always have a LF as a line ending

**Expected behavior**
at 3: use system-native line endings or at least make it configurable

**Your Environment**
In windows, I'm transferring logs and splitting them off between a couple of servers.

- td-agent fluentd 1.11.2
- Windows Server 2016

**Your Configuration**

```
<label @iis_text_logs>
  <match **>
    @type file
    path D:\Logs\IIS\W3SVC1\iis.%Y%m%dT%H%M%S%z
	append true
	<format>
	  @type single_value
	</format>
    <buffer>
      timekey 5s
      timekey_use_utc true
      timekey_wait 10s
	  path "D:\\Logs\\IIS\\W3SVC1\\buffer"
    </buffer>
   </match>
 </label>
```

**Your Error Log**
No errors.

**Additional context**
The reason for this curious configuration and the reason I'm hitting this is probably because I'm (ab)using fluentd to stream text logs from one server to another (as close to realtime as it will go - but buffer won't let me without writing billions of files...). The input is CRLF-terminated and the output needs to be CRLF-terminated as well for the follow-up tool that will then read the files. (and no, that tool cannot run on the source server, hence the setup)

### PR DESCRIPTION
**Pull request by cosmo0920**
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>

**Which issue(s) this PR fixes**: 
Fixes #3151 

**What this PR does / why we need it**: 
Currently, built-in formatter plugins use hard-coded LF newline.
We should provide CRLF style newline choice mainly for Windows users.

**Docs Changes**:
https://github.com/fluent/fluentd-docs-gitbook/pull/247

**Release Note**: 
Same as title.

### CODE REVIEW

File: lib/fluent/plugin/formatter_hash.rb [hunk 1]
```diff
@@ -22,10 +22,21 @@ class HashFormatter < Formatter
       Plugin.register_formatter('hash', self)
 
       config_param :add_newline, :bool, default: true
+      config_param :newline, :enum, list: [:lf, :crlf], default: :lf
```
Comment (repeatedly) [inline lib/fluent/plugin/formatter_hash.rb:25]: How about using `Fluent.windows?` for changing default for windows?

In addition, `newline` code are duplicated in many places. How about providing mixin in Formatter?

Comment (cosmo0920) [reply lib/fluent/plugin/formatter_hash.rb]: I'd applied the above suggestion as https://github.com/fluent/fluentd/pull/3152/commits/0943b1436a2882c5d0980c223b34e8f374661ecc and https://github.com/fluent/fluentd/pull/3152/commits/fdcfaf4ec0c5abd4a28c535e577541305b60f0e7.

**Comment by repeatedly** [comment]
Looks good 👍

**Comment by cosmo0920** [comment]
Let's shipping! :shipit:
