### PR TITLE
Fix logs when retrying

### LINKED ISSUE #2201: The value of next_retry_seconds outputted in the log is not the next try_flush time.
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.      : td-agent 3.2.1-0 ( fluentd 1.2.6 )
- Environment information, e.g. OS. : Ubuntu Trusty
- Your configuration                : out_forward only
- Your problem explanation. If you have an error logs, write it together.

In fluentd v1, the value of `next_retry_seconds` outputted in the log is not the next `try_flush` time.

td-agent.conf
```
<source>
  @type forward
</source>

<match test>
  @type forward
  <server>
    host xxx.xxx.xxx.xxx
  </server>
  buffer_type file
  buffer_path /var/log/td-agent/buffer/test
  flush_interval 10s
</match>
```

v0.12
```
# version
$ dpkg -l |grep td-agent
ii  td-agent                         2.5.0-0                             amd64        Treasure Agent: A data collector for Treasure Data
$ td-agent-gem list |grep 'fluentd '
fluentd (0.12.43)


# td-agent.log
2018-12-01 14:41:44 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-12-01 14:41:52 +0000 error_class="Errno::ECONNREFUSED" error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224" plugin_id="object:3ff5ba380870"
2018-12-01 14:41:52 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-12-01 14:42:09 +0000 error_class="Errno::ECONNREFUSED" error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224" plugin_id="object:3ff5ba380870"
2018-12-01 14:42:09 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-12-01 14:42:39 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3ff5ba380870"
2018-12-01 14:42:39 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-12-01 14:43:36 +0000 error_class="RuntimeError" error="no nodes are available" plugin_id="object:3ff5ba380870"
```

v1
```
# version
$ dpkg -l |grep td-agent
ii  td-agent                         3.2.1-0                             amd64        Treasure Agent: A data collector for Treasure Data
$ td-agent-gem list |grep fluentd
fluentd (1.2.6)

# td-agent.log
2018-12-01 14:50:36 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-12-01 14:50:36 +0000 chunk="57bf7091c5513bb7aecc0b69a2da6f06" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224"
2018-12-01 14:50:38 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2018-12-01 14:50:38 +0000 chunk="57bf7091c5513bb7aecc0b69a2da6f06" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224"
2018-12-01 14:50:42 +0000 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2018-12-01 14:50:42 +0000 chunk="57bf7091c5513bb7aecc0b69a2da6f06" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224"
2018-12-01 14:50:49 +0000 [warn]: #0 failed to flush the buffer. retry_time=4 next_retry_seconds=2018-12-01 14:50:49 +0000 chunk="57bf7091c5513bb7aecc0b69a2da6f06" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224"
2018-12-01 14:51:06 +0000 [warn]: #0 failed to flush the buffer. retry_time=5 next_retry_seconds=2018-12-01 14:51:06 +0000 chunk="57bf7091c5513bb7aecc0b69a2da6f06" error_class=Fluent::Plugin::ForwardOutput::NoNodesAvailable error="no nodes are available"
```

I think that it is caused by outputting a message before `@retry.step`. 
[fluentd/output.rb at v1.3.1 · fluent/fluentd · GitHub](https://github.com/fluent/fluentd/blob/v1.3.1/lib/fluent/plugin/output.rb#L1247)

With the fix, I did not know how much it would affect the retry logic. So I reported.

### PR DESCRIPTION
**Pull request by okkez**
In the previous version, the timestamp of next_retry_seconds is the same
as logs when retrying.

Fix #2201

### CODE REVIEW

File: lib/fluent/plugin/output.rb [hunk 1]
```diff
@@ -1222,29 +1222,29 @@ def update_retry_state(chunk_id, using_secondary, error = nil)
...
-          if @retry.limit?
             @buffer.clear_queue!
             log.debug "buffer queue cleared"
             @retry = nil
           else
             @retry.step
+            if error
+              if using_secondary
+                msg = "failed to flush the buffer with secondary output."
+                log.warn msg, retry_time: @retry.steps, next_retry_seconds: @retry.next_time, chunk: chunk_id_hex, error: error
```
Comment (repeatedly) [inline lib/fluent/plugin/output.rb]: Do we need to add `- 1` to `retry_time`?

Comment (tatsu-yam) [reply lib/fluent/plugin/output.rb]: When `write` fails for the first time, the `retry_time` starts from 0.
Rather, `retry_time` was displayed as 0 even though it was the first retry.
I think `retry_time=0` should not be output twice.
(In [#2201](https://github.com/fluent/fluentd/issues/2201),  the logs was not enough, I am sorry.)
```
2018-12-06 04:12:29 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-12-06 04:12:30 +0000 chunk="57c52b4ef75540aa1bc46190486ae4b8" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224"
  2018-12-06 04:12:29 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin_helper/socket.rb:59:in `initialize'
  2018-12-06 04:12:29 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.2.6/lib/fluent/plugin_helper/socket.rb:59:in `new'
...
2018-12-06 04:12:30 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-12-06 04:12:30 +0000 chunk="57c52b4ef75540aa1bc46190486ae4b8" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224"
2018-12-06 04:12:31 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-12-06 04:12:31 +0000 chunk="57c52b4ef75540aa1bc46190486ae4b8" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224"
2018-12-06 04:12:33 +0000 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2018-12-06 04:12:33 +0000 chunk="57c52b4ef75540aa1bc46190486ae4b8" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224"
2018-12-06 04:12:37 +0000 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2018-12-06 04:12:37 +0000 chunk="57c52b4ef75540aa1bc46190486ae4b8" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxx.xxx.xxx.xxx\" port 24224"
```

Comment (okkez) [reply lib/fluent/plugin/output.rb]: > Do we need to add - 1 to retry_time?

No. `retry_time` starts from 0. Display `retry_time=0` when Fluentd calls `try_flush` first time.

In this version, logs like following:

```
2018-12-06 14:46:29 +0900 [info]: #0 fluentd worker is now running worker=0
2018-12-06 14:46:31 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-12-06 14:46:32 +0900 chunk="57
c5405353f5e55d61ab8bfaad92b44d" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"::1\" port 24224"
  2018-12-06 14:46:31 +0900 [warn]: #0 /home/kenji/ruby/td-family/fluentd/lib/fluent/plugin_helper/socket.rb:59:in `initialize'
  (snip)
2018-12-06 14:46:32 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-12-06 14:46:32 +0900 chunk="57c5405353f5e55d61ab8bfaad92b44d" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"::1\" port 24224"
  2018-12-06 14:46:32 +0900 [warn]: #0 suppressed same stacktrace
2018-12-06 14:46:33 +0900 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-12-06 14:46:33 +0900 chunk="57c5405353f5e55d61ab8bfaad92b44d" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"::1\" port 24224"
  2018-12-06 14:46:33 +0900 [warn]: #0 suppressed same stacktrace
2018-12-06 14:46:35 +0900 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2018-12-06 14:46:35 +0900 chunk="57c5405353f5e55d61ab8bfaad92b44d" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"::1\" port 24224"
  2018-12-06 14:46:35 +0900 [warn]: #0 suppressed same stacktrace

```

Comment (repeatedly) [reply lib/fluent/plugin/output.rb]: Hmm... I see.
Looks like printing `retry_time=0` twice and same next_retry_seconds are weird.
`retry_time` should be start 1?

Comment (okkez) [reply lib/fluent/plugin/output.rb]: Sorry. I've pasted wrong logs...

```
2018-12-10 10:43:28 +0900 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-12-10 10:43:29 +0900 chunk="57
ca1174ccb6423c5465ec3e1b696a98" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"::1\" port 24224"
(snip)
2018-12-10 10:43:29 +0900 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-12-10 10:43:30 +0900 chunk="57ca1174ccb6423c5465ec3e1b696a98" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"::1\" port 24224"
  2018-12-10 10:43:29 +0900 [warn]: #0 suppressed same stacktrace
2018-12-10 10:43:30 +0900 [warn]: #0 failed to flush the buffer. retry_time=2 next_retry_seconds=2018-12-10 10:43:32 +0900 chunk="57ca1174ccb6423c5465ec3e1b696a98" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"::1\" port 24224"
  2018-12-10 10:43:30 +0900 [warn]: #0 suppressed same stacktrace
2018-12-10 10:43:32 +0900 [warn]: #0 failed to flush the buffer. retry_time=3 next_retry_seconds=2018-12-10 10:43:36 +0900 chunk="57ca1174ccb6423c5465ec3e1b696a98" error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"::1\" port 24224"
  2018-12-10 10:43:32 +0900 [warn]: #0 suppressed same stacktrace
```

**Comment by repeatedly** [comment]
@okkez Could you sqush commits into one?

**Comment by okkez** [comment]
Squash commits and force pushed.

**Comment by repeatedly** [comment]
Thx!

**Comment by tatsu-yam** [comment]
👍
