### PR TITLE
TLSServer: Fix crash on logging errors

### LINKED ISSUE #3475: Fluentd 4.1.1 is crashing on logging TLS errors
### Describe the bug

Fluentd 4.1.1 thread exits sometime, trying to log TLS errors.
Fluentd 4.1.0 is working fine (just logs an error and continue working).

### To Reproduce

looks like this behavior is introduced here: https://github.com/fluent/fluentd/commit/53df5d9d6b464e878689a8ae3f89ad40dbc82bec

### Expected behavior

FluentD shouldn't crash on logging

### Your Environment

```markdown
- Fluentd version: 4.1.1
- Operating system: Ubuntu 18.0.4
```

### Your Configuration

```aconf
<source>
  @id forward
  @type forward
  port 24224
  <security>
    self_hostname xxx
    shared_key xxx
  </security>
  <transport tls>
    version TLSv1_2
    insecure false
    ca_path /etc/td-agent/ca.crt
    cert_path /etc/td-agent/server.crt
    private_key_path /etc/td-agent/server.key
    client_cert_auth true
  </transport>
</source>
```

### Your Error Log

```shell
2021-07-29 12:24:01 +0000 [warn]: #1 [forward] thread exited by unexpected error plugin=Fluent::Plugin::ForwardInput title=:event_loop error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"
2021-07-29 12:24:01 +0000 [error]: #1 unexpected error error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/2.7.0/openssl/ssl.rb:239:in `peeraddr'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/2.7.0/openssl/ssl.rb:239:in `peeraddr'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/server.rb:713:in `rescue in try_tls_accept'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/server.rb:696:in `try_tls_accept'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/server.rb:726:in `on_connect'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/server.rb:41:in `on_connection'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/listener.rb:46:in `on_readable'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2021-07-29 12:24:01 +0000 [error]: #1 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-07-29 12:24:01 +0000 [error]: #1 unexpected error error_class=Errno::ENOTCONN error="Transport endpoint is not connected - getpeername(2)"
  2021-07-29 12:24:01 +0000 [error]: #1 suppressed same stacktrace
```

### Additional context

It's AliCloud :( And here are a lot of issues with TLS.

### PR DESCRIPTION
**Pull request by ashie**
**Which issue(s) this PR fixes**: 
Fixes #3475

**What this PR does / why we need it**: 
In #3330 we added host name information to the error messages but it
doesn't care the case when it fails `getpeername(2)`.

**Docs Changes**:
None

**Release Note**: 
Same with the title.

### CODE REVIEW

**Comment by kenhys** [comment]
I'll look.

**Review by cosmo0920 — APPROVED** [review]
Looks reasonable.

File: lib/fluent/plugin_helper/server.rb [hunk 1]
```diff
@@ -709,13 +709,15 @@ def try_tls_accept
                 return true
               end
             rescue Errno::EPIPE, Errno::ECONNRESET, Errno::ETIMEDOUT, Errno::ECONNREFUSED, Errno::EHOSTUNREACH => e
+              peeraddr = (@_handler_socket.peeraddr rescue PEERADDR_FAILED)
               @log.trace "unexpected error before accepting TLS connection",
```
Comment (kenhys) [inline lib/fluent/plugin_helper/server.rb:713]: I may be wrong, I thought that `@_handler_socket.peeraddr` (derived from  OpenSSL::SSL::SocketForwarder#peeraddr) will raise Errno::EXXX. 
Will `rescue PEERADDR_FAILED` work as expectedly?

Comment (kenhys) [reply lib/fluent/plugin_helper/server.rb:713]: (I know this idiom `rescue PEERADDR_FAILED` is used in other code, but I'm not sure it can be used here, too)

Comment (cosmo0920) [reply lib/fluent/plugin_helper/server.rb:713]: Hmm, `#peeraddr` and `PEERADDR_FAILED` returned array format is same but I'm not aware of exceptions from `@_handler_socket.peeraddr`.
OpenSSL's `peeraddr` is defined in https://github.com/ruby/openssl/blob/master/lib/openssl/ssl.rb#L246.
And this methods behavior is same for [IPSocket#peeraddr](https://docs.ruby-lang.org/ja/latest/method/IPSocket/i/peeraddr.html):
https://docs.ruby-lang.org/ja/latest/method/OpenSSL=3a=3aSSL=3a=3aSocketForwarder/i/peeraddr.html

Comment (cosmo0920) [reply lib/fluent/plugin_helper/server.rb:713]: Yeah, we should catch `Errno::EXXX` exceptions:
https://pubs.opengroup.org/onlinepubs/009695399/functions/getpeername.html
This exceptions should be from getpeername(2):
https://pubs.opengroup.org/onlinepubs/009695399/functions/getpeername.html

Comment (ashie) [reply lib/fluent/plugin_helper/server.rb:713]: Sorry, I don't understand what do you worry.
Do you worry whether `foo rescue bar` idiom works also against `Errno::EXXX`?
I confirmed that it works as expected:
```ruby
irb(main):001:0> PEERADDR_FAILED = ["?", "?", "name resolution failed", "?"]
=> ["?", "?", "name resolution failed", "?"]
irb(main):002:1* def peeraddr
irb(main):003:1*   raise Errno::ENOTCONN
irb(main):004:0> end
=> :peeraddr
irb(main):005:0> a = (peeraddr rescue PEERADDR_FAILED)
=> ["?", "?", "name resolution failed", "?"]
irb(main):006:0> b = peeraddr
Traceback (most recent call last):
        5: from /usr/bin/irb:23:in `<main>'
        4: from /usr/bin/irb:23:in `load'
        3: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        2: from (irb):6
        1: from (irb):3:in `peeraddr'
Errno::ENOTCONN (Transport endpoint is not connected)
```

Comment (kenhys) [reply lib/fluent/plugin_helper/server.rb:713]: Thanks, surely it works as expected. I've misunderstood `oo rescue bar` behavior.

**Review by kenhys — APPROVED** [review]
LGTM.

File: lib/fluent/plugin_helper/server.rb (hunk 1 above)
Comment (cosmo0920) [reply lib/fluent/plugin_helper/server.rb:713]: Thanks. Errno exceptions inherit `StandardError`. So, it works as expected.
https://github.com/fluent/fluentd/pull/3484
